#pragma once
#ifndef MIQT_QT_GEN_QTOOLBAR_H
#define MIQT_QT_GEN_QTOOLBAR_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "../libmiqt/libmiqt.h"
extern "C" {
typedef struct QAction QAction;
typedef struct QActionEvent QActionEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QRect QRect;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionToolBar QStyleOptionToolBar;
typedef struct QTabletEvent QTabletEvent;
typedef struct QToolBar QToolBar;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
typedef struct _GUID _GUID;
typedef struct type_info type_info;

extern __declspec(dllexport) void _GUID_Delete(_GUID* self, bool isSubclass);

extern __declspec(dllexport) void type_info_Delete(type_info* self, bool isSubclass);

extern __declspec(dllexport) QToolBar* QToolBar_new(QWidget* parent);
extern __declspec(dllexport) QToolBar* QToolBar_new2(struct miqt_string title);
extern __declspec(dllexport) QToolBar* QToolBar_new3();
extern __declspec(dllexport) QToolBar* QToolBar_new4(struct miqt_string title, QWidget* parent);
extern __declspec(dllexport) void QToolBar_virtbase(QToolBar* src, QWidget** outptr_QWidget);
extern __declspec(dllexport) QMetaObject* QToolBar_MetaObject(const QToolBar* self);
extern __declspec(dllexport) void* QToolBar_Metacast(QToolBar* self, const char* param1);
extern __declspec(dllexport) struct miqt_string QToolBar_Tr(const char* s);
extern __declspec(dllexport) void QToolBar_SetMovable(QToolBar* self, bool movable);
extern __declspec(dllexport) bool QToolBar_IsMovable(const QToolBar* self);
extern __declspec(dllexport) void QToolBar_SetAllowedAreas(QToolBar* self, int areas);
extern __declspec(dllexport) int QToolBar_AllowedAreas(const QToolBar* self);
extern __declspec(dllexport) bool QToolBar_IsAreaAllowed(const QToolBar* self, int area);
extern __declspec(dllexport) void QToolBar_SetOrientation(QToolBar* self, int orientation);
extern __declspec(dllexport) int QToolBar_Orientation(const QToolBar* self);
extern __declspec(dllexport) void QToolBar_Clear(QToolBar* self);
extern __declspec(dllexport) QAction* QToolBar_AddSeparator(QToolBar* self);
extern __declspec(dllexport) QAction* QToolBar_InsertSeparator(QToolBar* self, QAction* before);
extern __declspec(dllexport) QAction* QToolBar_AddWidget(QToolBar* self, QWidget* widget);
extern __declspec(dllexport) QAction* QToolBar_InsertWidget(QToolBar* self, QAction* before, QWidget* widget);
extern __declspec(dllexport) QRect* QToolBar_ActionGeometry(const QToolBar* self, QAction* action);
extern __declspec(dllexport) QAction* QToolBar_ActionAt(const QToolBar* self, QPoint* p);
extern __declspec(dllexport) QAction* QToolBar_ActionAt2(const QToolBar* self, int x, int y);
extern __declspec(dllexport) QAction* QToolBar_ToggleViewAction(const QToolBar* self);
extern __declspec(dllexport) QSize* QToolBar_IconSize(const QToolBar* self);
extern __declspec(dllexport) int QToolBar_ToolButtonStyle(const QToolBar* self);
extern __declspec(dllexport) QWidget* QToolBar_WidgetForAction(const QToolBar* self, QAction* action);
extern __declspec(dllexport) bool QToolBar_IsFloatable(const QToolBar* self);
extern __declspec(dllexport) void QToolBar_SetFloatable(QToolBar* self, bool floatable);
extern __declspec(dllexport) bool QToolBar_IsFloating(const QToolBar* self);
extern __declspec(dllexport) void QToolBar_SetIconSize(QToolBar* self, QSize* iconSize);
extern __declspec(dllexport) void QToolBar_SetToolButtonStyle(QToolBar* self, int toolButtonStyle);
extern __declspec(dllexport) void QToolBar_ActionTriggered(QToolBar* self, QAction* action);
void QToolBar_connect_ActionTriggered(QToolBar* self, intptr_t slot);
extern __declspec(dllexport) void QToolBar_MovableChanged(QToolBar* self, bool movable);
void QToolBar_connect_MovableChanged(QToolBar* self, intptr_t slot);
extern __declspec(dllexport) void QToolBar_AllowedAreasChanged(QToolBar* self, int allowedAreas);
void QToolBar_connect_AllowedAreasChanged(QToolBar* self, intptr_t slot);
extern __declspec(dllexport) void QToolBar_OrientationChanged(QToolBar* self, int orientation);
void QToolBar_connect_OrientationChanged(QToolBar* self, intptr_t slot);
extern __declspec(dllexport) void QToolBar_IconSizeChanged(QToolBar* self, QSize* iconSize);
void QToolBar_connect_IconSizeChanged(QToolBar* self, intptr_t slot);
extern __declspec(dllexport) void QToolBar_ToolButtonStyleChanged(QToolBar* self, int toolButtonStyle);
void QToolBar_connect_ToolButtonStyleChanged(QToolBar* self, intptr_t slot);
extern __declspec(dllexport) void QToolBar_TopLevelChanged(QToolBar* self, bool topLevel);
void QToolBar_connect_TopLevelChanged(QToolBar* self, intptr_t slot);
extern __declspec(dllexport) void QToolBar_VisibilityChanged(QToolBar* self, bool visible);
void QToolBar_connect_VisibilityChanged(QToolBar* self, intptr_t slot);
extern __declspec(dllexport) void QToolBar_ActionEvent(QToolBar* self, QActionEvent* event);
extern __declspec(dllexport) void QToolBar_ChangeEvent(QToolBar* self, QEvent* event);
extern __declspec(dllexport) void QToolBar_PaintEvent(QToolBar* self, QPaintEvent* event);
extern __declspec(dllexport) bool QToolBar_Event(QToolBar* self, QEvent* event);
extern __declspec(dllexport) void QToolBar_InitStyleOption(const QToolBar* self, QStyleOptionToolBar* option);
extern __declspec(dllexport) struct miqt_string QToolBar_Tr2(const char* s, const char* c);
extern __declspec(dllexport) struct miqt_string QToolBar_Tr3(const char* s, const char* c, int n);
extern __declspec(dllexport) void QToolBar_override_virtual_ActionEvent(void* self, intptr_t slot);
void QToolBar_virtualbase_ActionEvent(void* self, QActionEvent* event);
extern __declspec(dllexport) void QToolBar_override_virtual_ChangeEvent(void* self, intptr_t slot);
void QToolBar_virtualbase_ChangeEvent(void* self, QEvent* event);
extern __declspec(dllexport) void QToolBar_override_virtual_PaintEvent(void* self, intptr_t slot);
void QToolBar_virtualbase_PaintEvent(void* self, QPaintEvent* event);
extern __declspec(dllexport) void QToolBar_override_virtual_Event(void* self, intptr_t slot);
bool QToolBar_virtualbase_Event(void* self, QEvent* event);
extern __declspec(dllexport) void QToolBar_override_virtual_InitStyleOption(void* self, intptr_t slot);
void QToolBar_virtualbase_InitStyleOption(const void* self, QStyleOptionToolBar* option);
extern __declspec(dllexport) void QToolBar_override_virtual_DevType(void* self, intptr_t slot);
int QToolBar_virtualbase_DevType(const void* self);
extern __declspec(dllexport) void QToolBar_override_virtual_SetVisible(void* self, intptr_t slot);
void QToolBar_virtualbase_SetVisible(void* self, bool visible);
extern __declspec(dllexport) void QToolBar_override_virtual_SizeHint(void* self, intptr_t slot);
QSize* QToolBar_virtualbase_SizeHint(const void* self);
extern __declspec(dllexport) void QToolBar_override_virtual_MinimumSizeHint(void* self, intptr_t slot);
QSize* QToolBar_virtualbase_MinimumSizeHint(const void* self);
extern __declspec(dllexport) void QToolBar_override_virtual_HeightForWidth(void* self, intptr_t slot);
int QToolBar_virtualbase_HeightForWidth(const void* self, int param1);
extern __declspec(dllexport) void QToolBar_override_virtual_HasHeightForWidth(void* self, intptr_t slot);
bool QToolBar_virtualbase_HasHeightForWidth(const void* self);
extern __declspec(dllexport) void QToolBar_override_virtual_PaintEngine(void* self, intptr_t slot);
QPaintEngine* QToolBar_virtualbase_PaintEngine(const void* self);
extern __declspec(dllexport) void QToolBar_override_virtual_MousePressEvent(void* self, intptr_t slot);
void QToolBar_virtualbase_MousePressEvent(void* self, QMouseEvent* event);
extern __declspec(dllexport) void QToolBar_override_virtual_MouseReleaseEvent(void* self, intptr_t slot);
void QToolBar_virtualbase_MouseReleaseEvent(void* self, QMouseEvent* event);
extern __declspec(dllexport) void QToolBar_override_virtual_MouseDoubleClickEvent(void* self, intptr_t slot);
void QToolBar_virtualbase_MouseDoubleClickEvent(void* self, QMouseEvent* event);
extern __declspec(dllexport) void QToolBar_override_virtual_MouseMoveEvent(void* self, intptr_t slot);
void QToolBar_virtualbase_MouseMoveEvent(void* self, QMouseEvent* event);
extern __declspec(dllexport) void QToolBar_override_virtual_WheelEvent(void* self, intptr_t slot);
void QToolBar_virtualbase_WheelEvent(void* self, QWheelEvent* event);
extern __declspec(dllexport) void QToolBar_override_virtual_KeyPressEvent(void* self, intptr_t slot);
void QToolBar_virtualbase_KeyPressEvent(void* self, QKeyEvent* event);
extern __declspec(dllexport) void QToolBar_override_virtual_KeyReleaseEvent(void* self, intptr_t slot);
void QToolBar_virtualbase_KeyReleaseEvent(void* self, QKeyEvent* event);
extern __declspec(dllexport) void QToolBar_override_virtual_FocusInEvent(void* self, intptr_t slot);
void QToolBar_virtualbase_FocusInEvent(void* self, QFocusEvent* event);
extern __declspec(dllexport) void QToolBar_override_virtual_FocusOutEvent(void* self, intptr_t slot);
void QToolBar_virtualbase_FocusOutEvent(void* self, QFocusEvent* event);
extern __declspec(dllexport) void QToolBar_override_virtual_EnterEvent(void* self, intptr_t slot);
void QToolBar_virtualbase_EnterEvent(void* self, QEnterEvent* event);
extern __declspec(dllexport) void QToolBar_override_virtual_LeaveEvent(void* self, intptr_t slot);
void QToolBar_virtualbase_LeaveEvent(void* self, QEvent* event);
extern __declspec(dllexport) void QToolBar_override_virtual_MoveEvent(void* self, intptr_t slot);
void QToolBar_virtualbase_MoveEvent(void* self, QMoveEvent* event);
extern __declspec(dllexport) void QToolBar_override_virtual_ResizeEvent(void* self, intptr_t slot);
void QToolBar_virtualbase_ResizeEvent(void* self, QResizeEvent* event);
extern __declspec(dllexport) void QToolBar_override_virtual_CloseEvent(void* self, intptr_t slot);
void QToolBar_virtualbase_CloseEvent(void* self, QCloseEvent* event);
extern __declspec(dllexport) void QToolBar_override_virtual_ContextMenuEvent(void* self, intptr_t slot);
void QToolBar_virtualbase_ContextMenuEvent(void* self, QContextMenuEvent* event);
extern __declspec(dllexport) void QToolBar_override_virtual_TabletEvent(void* self, intptr_t slot);
void QToolBar_virtualbase_TabletEvent(void* self, QTabletEvent* event);
extern __declspec(dllexport) void QToolBar_override_virtual_DragEnterEvent(void* self, intptr_t slot);
void QToolBar_virtualbase_DragEnterEvent(void* self, QDragEnterEvent* event);
extern __declspec(dllexport) void QToolBar_override_virtual_DragMoveEvent(void* self, intptr_t slot);
void QToolBar_virtualbase_DragMoveEvent(void* self, QDragMoveEvent* event);
extern __declspec(dllexport) void QToolBar_override_virtual_DragLeaveEvent(void* self, intptr_t slot);
void QToolBar_virtualbase_DragLeaveEvent(void* self, QDragLeaveEvent* event);
extern __declspec(dllexport) void QToolBar_override_virtual_DropEvent(void* self, intptr_t slot);
void QToolBar_virtualbase_DropEvent(void* self, QDropEvent* event);
extern __declspec(dllexport) void QToolBar_override_virtual_ShowEvent(void* self, intptr_t slot);
void QToolBar_virtualbase_ShowEvent(void* self, QShowEvent* event);
extern __declspec(dllexport) void QToolBar_override_virtual_HideEvent(void* self, intptr_t slot);
void QToolBar_virtualbase_HideEvent(void* self, QHideEvent* event);
extern __declspec(dllexport) void QToolBar_override_virtual_NativeEvent(void* self, intptr_t slot);
bool QToolBar_virtualbase_NativeEvent(void* self, struct miqt_string eventType, void* message, intptr_t* result);
extern __declspec(dllexport) void QToolBar_override_virtual_Metric(void* self, intptr_t slot);
int QToolBar_virtualbase_Metric(const void* self, PaintDeviceMetric param1);
extern __declspec(dllexport) void QToolBar_override_virtual_InitPainter(void* self, intptr_t slot);
void QToolBar_virtualbase_InitPainter(const void* self, QPainter* painter);
extern __declspec(dllexport) void QToolBar_override_virtual_Redirected(void* self, intptr_t slot);
QPaintDevice* QToolBar_virtualbase_Redirected(const void* self, QPoint* offset);
extern __declspec(dllexport) void QToolBar_override_virtual_SharedPainter(void* self, intptr_t slot);
QPainter* QToolBar_virtualbase_SharedPainter(const void* self);
extern __declspec(dllexport) void QToolBar_override_virtual_InputMethodEvent(void* self, intptr_t slot);
void QToolBar_virtualbase_InputMethodEvent(void* self, QInputMethodEvent* param1);
extern __declspec(dllexport) void QToolBar_override_virtual_InputMethodQuery(void* self, intptr_t slot);
QVariant* QToolBar_virtualbase_InputMethodQuery(const void* self, int param1);
extern __declspec(dllexport) void QToolBar_override_virtual_FocusNextPrevChild(void* self, intptr_t slot);
bool QToolBar_virtualbase_FocusNextPrevChild(void* self, bool next);
extern __declspec(dllexport) void QToolBar_Delete(QToolBar* self, bool isSubclass);

} 
