#pragma once
#ifndef MIQT_QT_GEN_QCOLUMNVIEW_H
#define MIQT_QT_GEN_QCOLUMNVIEW_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "../libmiqt/libmiqt.h"
extern "C" {
typedef struct QAbstractItemDelegate QAbstractItemDelegate;
typedef struct QAbstractItemModel QAbstractItemModel;
typedef struct QAbstractItemView QAbstractItemView;
typedef struct QAbstractScrollArea QAbstractScrollArea;
typedef struct QColumnView QColumnView;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFrame QFrame;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QItemSelection QItemSelection;
typedef struct QItemSelectionModel QItemSelectionModel;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaObject QMetaObject;
typedef struct QModelIndex QModelIndex;
typedef struct QMouseEvent QMouseEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPoint QPoint;
typedef struct QRect QRect;
typedef struct QRegion QRegion;
typedef struct QResizeEvent QResizeEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionViewItem QStyleOptionViewItem;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWidget QWidget;

extern __declspec(dllexport) void _GUID_Delete(_GUID* self, bool isSubclass);

extern __declspec(dllexport) void type_info_Delete(type_info* self, bool isSubclass);

extern __declspec(dllexport) QColumnView* QColumnView_new(QWidget* parent);
extern __declspec(dllexport) QColumnView* QColumnView_new2();
extern __declspec(dllexport) void QColumnView_virtbase(QColumnView* src, QAbstractItemView** outptr_QAbstractItemView);
extern __declspec(dllexport) QMetaObject* QColumnView_MetaObject(const QColumnView* self);
extern __declspec(dllexport) void* QColumnView_Metacast(QColumnView* self, const char* param1);
extern __declspec(dllexport) struct miqt_string QColumnView_Tr(const char* s);
extern __declspec(dllexport) void QColumnView_UpdatePreviewWidget(QColumnView* self, QModelIndex* index);
void QColumnView_connect_UpdatePreviewWidget(QColumnView* self, intptr_t slot);
extern __declspec(dllexport) QModelIndex* QColumnView_IndexAt(const QColumnView* self, QPoint* point);
extern __declspec(dllexport) void QColumnView_ScrollTo(QColumnView* self, QModelIndex* index, ScrollHint hint);
extern __declspec(dllexport) QSize* QColumnView_SizeHint(const QColumnView* self);
extern __declspec(dllexport) QRect* QColumnView_VisualRect(const QColumnView* self, QModelIndex* index);
extern __declspec(dllexport) void QColumnView_SetModel(QColumnView* self, QAbstractItemModel* model);
extern __declspec(dllexport) void QColumnView_SetSelectionModel(QColumnView* self, QItemSelectionModel* selectionModel);
extern __declspec(dllexport) void QColumnView_SetRootIndex(QColumnView* self, QModelIndex* index);
extern __declspec(dllexport) void QColumnView_SelectAll(QColumnView* self);
extern __declspec(dllexport) void QColumnView_SetResizeGripsVisible(QColumnView* self, bool visible);
extern __declspec(dllexport) bool QColumnView_ResizeGripsVisible(const QColumnView* self);
extern __declspec(dllexport) QWidget* QColumnView_PreviewWidget(const QColumnView* self);
extern __declspec(dllexport) void QColumnView_SetPreviewWidget(QColumnView* self, QWidget* widget);
extern __declspec(dllexport) void QColumnView_SetColumnWidths(QColumnView* self, struct miqt_array /* of int */  list);
extern __declspec(dllexport) struct miqt_array /* of int */  QColumnView_ColumnWidths(const QColumnView* self);
extern __declspec(dllexport) bool QColumnView_IsIndexHidden(const QColumnView* self, QModelIndex* index);
extern __declspec(dllexport) QModelIndex* QColumnView_MoveCursor(QColumnView* self, CursorAction cursorAction, int modifiers);
extern __declspec(dllexport) void QColumnView_ResizeEvent(QColumnView* self, QResizeEvent* event);
extern __declspec(dllexport) void QColumnView_SetSelection(QColumnView* self, QRect* rect, int command);
extern __declspec(dllexport) QRegion* QColumnView_VisualRegionForSelection(const QColumnView* self, QItemSelection* selection);
extern __declspec(dllexport) int QColumnView_HorizontalOffset(const QColumnView* self);
extern __declspec(dllexport) int QColumnView_VerticalOffset(const QColumnView* self);
extern __declspec(dllexport) void QColumnView_RowsInserted(QColumnView* self, QModelIndex* parent, int start, int end);
extern __declspec(dllexport) void QColumnView_CurrentChanged(QColumnView* self, QModelIndex* current, QModelIndex* previous);
extern __declspec(dllexport) void QColumnView_ScrollContentsBy(QColumnView* self, int dx, int dy);
extern __declspec(dllexport) QAbstractItemView* QColumnView_CreateColumn(QColumnView* self, QModelIndex* rootIndex);
extern __declspec(dllexport) struct miqt_string QColumnView_Tr2(const char* s, const char* c);
extern __declspec(dllexport) struct miqt_string QColumnView_Tr3(const char* s, const char* c, int n);
extern __declspec(dllexport) void QColumnView_override_virtual_IndexAt(void* self, intptr_t slot);
QModelIndex* QColumnView_virtualbase_IndexAt(const void* self, QPoint* point);
extern __declspec(dllexport) void QColumnView_override_virtual_ScrollTo(void* self, intptr_t slot);
void QColumnView_virtualbase_ScrollTo(void* self, QModelIndex* index, ScrollHint hint);
extern __declspec(dllexport) void QColumnView_override_virtual_SizeHint(void* self, intptr_t slot);
QSize* QColumnView_virtualbase_SizeHint(const void* self);
extern __declspec(dllexport) void QColumnView_override_virtual_VisualRect(void* self, intptr_t slot);
QRect* QColumnView_virtualbase_VisualRect(const void* self, QModelIndex* index);
extern __declspec(dllexport) void QColumnView_override_virtual_SetModel(void* self, intptr_t slot);
void QColumnView_virtualbase_SetModel(void* self, QAbstractItemModel* model);
extern __declspec(dllexport) void QColumnView_override_virtual_SetSelectionModel(void* self, intptr_t slot);
void QColumnView_virtualbase_SetSelectionModel(void* self, QItemSelectionModel* selectionModel);
extern __declspec(dllexport) void QColumnView_override_virtual_SetRootIndex(void* self, intptr_t slot);
void QColumnView_virtualbase_SetRootIndex(void* self, QModelIndex* index);
extern __declspec(dllexport) void QColumnView_override_virtual_SelectAll(void* self, intptr_t slot);
void QColumnView_virtualbase_SelectAll(void* self);
extern __declspec(dllexport) void QColumnView_override_virtual_IsIndexHidden(void* self, intptr_t slot);
bool QColumnView_virtualbase_IsIndexHidden(const void* self, QModelIndex* index);
extern __declspec(dllexport) void QColumnView_override_virtual_MoveCursor(void* self, intptr_t slot);
QModelIndex* QColumnView_virtualbase_MoveCursor(void* self, CursorAction cursorAction, int modifiers);
extern __declspec(dllexport) void QColumnView_override_virtual_ResizeEvent(void* self, intptr_t slot);
void QColumnView_virtualbase_ResizeEvent(void* self, QResizeEvent* event);
extern __declspec(dllexport) void QColumnView_override_virtual_SetSelection(void* self, intptr_t slot);
void QColumnView_virtualbase_SetSelection(void* self, QRect* rect, int command);
extern __declspec(dllexport) void QColumnView_override_virtual_VisualRegionForSelection(void* self, intptr_t slot);
QRegion* QColumnView_virtualbase_VisualRegionForSelection(const void* self, QItemSelection* selection);
extern __declspec(dllexport) void QColumnView_override_virtual_HorizontalOffset(void* self, intptr_t slot);
int QColumnView_virtualbase_HorizontalOffset(const void* self);
extern __declspec(dllexport) void QColumnView_override_virtual_VerticalOffset(void* self, intptr_t slot);
int QColumnView_virtualbase_VerticalOffset(const void* self);
extern __declspec(dllexport) void QColumnView_override_virtual_RowsInserted(void* self, intptr_t slot);
void QColumnView_virtualbase_RowsInserted(void* self, QModelIndex* parent, int start, int end);
extern __declspec(dllexport) void QColumnView_override_virtual_CurrentChanged(void* self, intptr_t slot);
void QColumnView_virtualbase_CurrentChanged(void* self, QModelIndex* current, QModelIndex* previous);
extern __declspec(dllexport) void QColumnView_override_virtual_ScrollContentsBy(void* self, intptr_t slot);
void QColumnView_virtualbase_ScrollContentsBy(void* self, int dx, int dy);
extern __declspec(dllexport) void QColumnView_override_virtual_CreateColumn(void* self, intptr_t slot);
QAbstractItemView* QColumnView_virtualbase_CreateColumn(void* self, QModelIndex* rootIndex);
extern __declspec(dllexport) void QColumnView_override_virtual_KeyboardSearch(void* self, intptr_t slot);
void QColumnView_virtualbase_KeyboardSearch(void* self, struct miqt_string search);
extern __declspec(dllexport) void QColumnView_override_virtual_SizeHintForRow(void* self, intptr_t slot);
int QColumnView_virtualbase_SizeHintForRow(const void* self, int row);
extern __declspec(dllexport) void QColumnView_override_virtual_SizeHintForColumn(void* self, intptr_t slot);
int QColumnView_virtualbase_SizeHintForColumn(const void* self, int column);
extern __declspec(dllexport) void QColumnView_override_virtual_ItemDelegateForIndex(void* self, intptr_t slot);
QAbstractItemDelegate* QColumnView_virtualbase_ItemDelegateForIndex(const void* self, QModelIndex* index);
extern __declspec(dllexport) void QColumnView_override_virtual_InputMethodQuery(void* self, intptr_t slot);
QVariant* QColumnView_virtualbase_InputMethodQuery(const void* self, int query);
extern __declspec(dllexport) void QColumnView_override_virtual_Reset(void* self, intptr_t slot);
void QColumnView_virtualbase_Reset(void* self);
extern __declspec(dllexport) void QColumnView_override_virtual_DoItemsLayout(void* self, intptr_t slot);
void QColumnView_virtualbase_DoItemsLayout(void* self);
extern __declspec(dllexport) void QColumnView_override_virtual_DataChanged(void* self, intptr_t slot);
void QColumnView_virtualbase_DataChanged(void* self, QModelIndex* topLeft, QModelIndex* bottomRight, struct miqt_array /* of int */  roles);
extern __declspec(dllexport) void QColumnView_override_virtual_RowsAboutToBeRemoved(void* self, intptr_t slot);
void QColumnView_virtualbase_RowsAboutToBeRemoved(void* self, QModelIndex* parent, int start, int end);
extern __declspec(dllexport) void QColumnView_override_virtual_SelectionChanged(void* self, intptr_t slot);
void QColumnView_virtualbase_SelectionChanged(void* self, QItemSelection* selected, QItemSelection* deselected);
extern __declspec(dllexport) void QColumnView_override_virtual_UpdateEditorData(void* self, intptr_t slot);
void QColumnView_virtualbase_UpdateEditorData(void* self);
extern __declspec(dllexport) void QColumnView_override_virtual_UpdateEditorGeometries(void* self, intptr_t slot);
void QColumnView_virtualbase_UpdateEditorGeometries(void* self);
extern __declspec(dllexport) void QColumnView_override_virtual_UpdateGeometries(void* self, intptr_t slot);
void QColumnView_virtualbase_UpdateGeometries(void* self);
extern __declspec(dllexport) void QColumnView_override_virtual_VerticalScrollbarAction(void* self, intptr_t slot);
void QColumnView_virtualbase_VerticalScrollbarAction(void* self, int action);
extern __declspec(dllexport) void QColumnView_override_virtual_HorizontalScrollbarAction(void* self, intptr_t slot);
void QColumnView_virtualbase_HorizontalScrollbarAction(void* self, int action);
extern __declspec(dllexport) void QColumnView_override_virtual_VerticalScrollbarValueChanged(void* self, intptr_t slot);
void QColumnView_virtualbase_VerticalScrollbarValueChanged(void* self, int value);
extern __declspec(dllexport) void QColumnView_override_virtual_HorizontalScrollbarValueChanged(void* self, intptr_t slot);
void QColumnView_virtualbase_HorizontalScrollbarValueChanged(void* self, int value);
extern __declspec(dllexport) void QColumnView_override_virtual_CloseEditor(void* self, intptr_t slot);
void QColumnView_virtualbase_CloseEditor(void* self, QWidget* editor, int hint);
extern __declspec(dllexport) void QColumnView_override_virtual_CommitData(void* self, intptr_t slot);
void QColumnView_virtualbase_CommitData(void* self, QWidget* editor);
extern __declspec(dllexport) void QColumnView_override_virtual_EditorDestroyed(void* self, intptr_t slot);
void QColumnView_virtualbase_EditorDestroyed(void* self, QObject* editor);
extern __declspec(dllexport) void QColumnView_override_virtual_SelectedIndexes(void* self, intptr_t slot);
struct miqt_array /* of QModelIndex* */  QColumnView_virtualbase_SelectedIndexes(const void* self);
extern __declspec(dllexport) void QColumnView_override_virtual_Edit2(void* self, intptr_t slot);
bool QColumnView_virtualbase_Edit2(void* self, QModelIndex* index, EditTrigger trigger, QEvent* event);
extern __declspec(dllexport) void QColumnView_override_virtual_SelectionCommand(void* self, intptr_t slot);
int QColumnView_virtualbase_SelectionCommand(const void* self, QModelIndex* index, QEvent* event);
extern __declspec(dllexport) void QColumnView_override_virtual_StartDrag(void* self, intptr_t slot);
void QColumnView_virtualbase_StartDrag(void* self, int supportedActions);
extern __declspec(dllexport) void QColumnView_override_virtual_InitViewItemOption(void* self, intptr_t slot);
void QColumnView_virtualbase_InitViewItemOption(const void* self, QStyleOptionViewItem* option);
extern __declspec(dllexport) void QColumnView_override_virtual_FocusNextPrevChild(void* self, intptr_t slot);
bool QColumnView_virtualbase_FocusNextPrevChild(void* self, bool next);
extern __declspec(dllexport) void QColumnView_override_virtual_Event(void* self, intptr_t slot);
bool QColumnView_virtualbase_Event(void* self, QEvent* event);
extern __declspec(dllexport) void QColumnView_override_virtual_ViewportEvent(void* self, intptr_t slot);
bool QColumnView_virtualbase_ViewportEvent(void* self, QEvent* event);
extern __declspec(dllexport) void QColumnView_override_virtual_MousePressEvent(void* self, intptr_t slot);
void QColumnView_virtualbase_MousePressEvent(void* self, QMouseEvent* event);
extern __declspec(dllexport) void QColumnView_override_virtual_MouseMoveEvent(void* self, intptr_t slot);
void QColumnView_virtualbase_MouseMoveEvent(void* self, QMouseEvent* event);
extern __declspec(dllexport) void QColumnView_override_virtual_MouseReleaseEvent(void* self, intptr_t slot);
void QColumnView_virtualbase_MouseReleaseEvent(void* self, QMouseEvent* event);
extern __declspec(dllexport) void QColumnView_override_virtual_MouseDoubleClickEvent(void* self, intptr_t slot);
void QColumnView_virtualbase_MouseDoubleClickEvent(void* self, QMouseEvent* event);
extern __declspec(dllexport) void QColumnView_override_virtual_DragEnterEvent(void* self, intptr_t slot);
void QColumnView_virtualbase_DragEnterEvent(void* self, QDragEnterEvent* event);
extern __declspec(dllexport) void QColumnView_override_virtual_DragMoveEvent(void* self, intptr_t slot);
void QColumnView_virtualbase_DragMoveEvent(void* self, QDragMoveEvent* event);
extern __declspec(dllexport) void QColumnView_override_virtual_DragLeaveEvent(void* self, intptr_t slot);
void QColumnView_virtualbase_DragLeaveEvent(void* self, QDragLeaveEvent* event);
extern __declspec(dllexport) void QColumnView_override_virtual_DropEvent(void* self, intptr_t slot);
void QColumnView_virtualbase_DropEvent(void* self, QDropEvent* event);
extern __declspec(dllexport) void QColumnView_override_virtual_FocusInEvent(void* self, intptr_t slot);
void QColumnView_virtualbase_FocusInEvent(void* self, QFocusEvent* event);
extern __declspec(dllexport) void QColumnView_override_virtual_FocusOutEvent(void* self, intptr_t slot);
void QColumnView_virtualbase_FocusOutEvent(void* self, QFocusEvent* event);
extern __declspec(dllexport) void QColumnView_override_virtual_KeyPressEvent(void* self, intptr_t slot);
void QColumnView_virtualbase_KeyPressEvent(void* self, QKeyEvent* event);
extern __declspec(dllexport) void QColumnView_override_virtual_TimerEvent(void* self, intptr_t slot);
void QColumnView_virtualbase_TimerEvent(void* self, QTimerEvent* event);
extern __declspec(dllexport) void QColumnView_override_virtual_InputMethodEvent(void* self, intptr_t slot);
void QColumnView_virtualbase_InputMethodEvent(void* self, QInputMethodEvent* event);
extern __declspec(dllexport) void QColumnView_override_virtual_EventFilter(void* self, intptr_t slot);
bool QColumnView_virtualbase_EventFilter(void* self, QObject* object, QEvent* event);
extern __declspec(dllexport) void QColumnView_override_virtual_ViewportSizeHint(void* self, intptr_t slot);
QSize* QColumnView_virtualbase_ViewportSizeHint(const void* self);
extern __declspec(dllexport) void QColumnView_Delete(QColumnView* self, bool isSubclass);

} 
