#pragma once
#ifndef MIQT_QT_GEN_QWIDGET_H
#define MIQT_QT_GEN_QWIDGET_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

//#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libmiqt/libmiqt.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAction;
class QActionEvent;
class QBackingStore;
class QBitmap;
class QChildEvent;
class QCloseEvent;
class QContextMenuEvent;
class QCursor;
class QDragEnterEvent;
class QDragLeaveEvent;
class QDragMoveEvent;
class QDropEvent;
class QEnterEvent;
class QEvent;
class QFocusEvent;
class QFont;
class QFontInfo;
class QFontMetrics;
class QGraphicsEffect;
class QGraphicsProxyWidget;
class QHideEvent;
class QIcon;
class QInputMethodEvent;
class QKeyEvent;
class QKeySequence;
class QLayout;
class QLocale;
class QMargins;
class QMetaMethod;
class QMetaObject;
class QMouseEvent;
class QMoveEvent;
class QObject;
class QPaintDevice;
class QPaintEngine;
class QPaintEvent;
class QPainter;
class QPalette;
class QPixmap;
class QPoint;
class QPointF;
class QRect;
class QRegion;
class QResizeEvent;
class QScreen;
class QShowEvent;
class QSize;
class QSizePolicy;
class QStyle;
class QTabletEvent;
class QTimerEvent;
class QVariant;
class QWheelEvent;
class QWidget;
class QWidgetData;
class QWindow;
class _GUID;
class type_info;
#else
typedef struct QAction QAction;
typedef struct QActionEvent QActionEvent;
typedef struct QBackingStore QBackingStore;
typedef struct QBitmap QBitmap;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QCursor QCursor;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFont QFont;
typedef struct QFontInfo QFontInfo;
typedef struct QFontMetrics QFontMetrics;
typedef struct QGraphicsEffect QGraphicsEffect;
typedef struct QGraphicsProxyWidget QGraphicsProxyWidget;
typedef struct QHideEvent QHideEvent;
typedef struct QIcon QIcon;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QKeySequence QKeySequence;
typedef struct QLayout QLayout;
typedef struct QLocale QLocale;
typedef struct QMargins QMargins;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPalette QPalette;
typedef struct QPixmap QPixmap;
typedef struct QPoint QPoint;
typedef struct QPointF QPointF;
typedef struct QRect QRect;
typedef struct QRegion QRegion;
typedef struct QResizeEvent QResizeEvent;
typedef struct QScreen QScreen;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QSizePolicy QSizePolicy;
typedef struct QStyle QStyle;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
typedef struct QWidgetData QWidgetData;
typedef struct QWindow QWindow;
typedef struct _GUID _GUID;
typedef struct type_info type_info;
#endif

extern __declspec(dllexport) void _GUID_Delete(_GUID* self, bool isSubclass);

extern __declspec(dllexport) void type_info_Delete(type_info* self, bool isSubclass);

extern __declspec(dllexport) QWidgetData* QWidgetData_new(QWidgetData* param1);
extern __declspec(dllexport) void QWidgetData_OperatorAssign(QWidgetData* self, QWidgetData* param1);
extern __declspec(dllexport) void QWidgetData_Delete(QWidgetData* self, bool isSubclass);

extern __declspec(dllexport) QWidget* QWidget_new(QWidget* parent);
extern __declspec(dllexport) QWidget* QWidget_new2();
extern __declspec(dllexport) QWidget* QWidget_new3(QWidget* parent, int f);
extern __declspec(dllexport) void QWidget_virtbase(QWidget* src, QObject** outptr_QObject, QPaintDevice** outptr_QPaintDevice);
extern __declspec(dllexport) QMetaObject* QWidget_MetaObject(const QWidget* self);
extern __declspec(dllexport) void* QWidget_Metacast(QWidget* self, const char* param1);
extern __declspec(dllexport) struct miqt_string QWidget_Tr(const char* s);
extern __declspec(dllexport) int QWidget_DevType(const QWidget* self);
extern __declspec(dllexport) uintptr_t QWidget_WinId(const QWidget* self);
extern __declspec(dllexport) void QWidget_CreateWinId(QWidget* self);
extern __declspec(dllexport) uintptr_t QWidget_InternalWinId(const QWidget* self);
extern __declspec(dllexport) uintptr_t QWidget_EffectiveWinId(const QWidget* self);
extern __declspec(dllexport) QStyle* QWidget_Style(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetStyle(QWidget* self, QStyle* style);
extern __declspec(dllexport) bool QWidget_IsTopLevel(const QWidget* self);
extern __declspec(dllexport) bool QWidget_IsWindow(const QWidget* self);
extern __declspec(dllexport) bool QWidget_IsModal(const QWidget* self);
extern __declspec(dllexport) int QWidget_WindowModality(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetWindowModality(QWidget* self, int windowModality);
extern __declspec(dllexport) bool QWidget_IsEnabled(const QWidget* self);
extern __declspec(dllexport) bool QWidget_IsEnabledTo(const QWidget* self, QWidget* param1);
extern __declspec(dllexport) void QWidget_SetEnabled(QWidget* self, bool enabled);
extern __declspec(dllexport) void QWidget_SetDisabled(QWidget* self, bool disabled);
extern __declspec(dllexport) void QWidget_SetWindowModified(QWidget* self, bool windowModified);
extern __declspec(dllexport) QRect* QWidget_FrameGeometry(const QWidget* self);
extern __declspec(dllexport) QRect* QWidget_Geometry(const QWidget* self);
extern __declspec(dllexport) QRect* QWidget_NormalGeometry(const QWidget* self);
extern __declspec(dllexport) int QWidget_X(const QWidget* self);
extern __declspec(dllexport) int QWidget_Y(const QWidget* self);
extern __declspec(dllexport) QPoint* QWidget_Pos(const QWidget* self);
extern __declspec(dllexport) QSize* QWidget_FrameSize(const QWidget* self);
extern __declspec(dllexport) QSize* QWidget_Size(const QWidget* self);
extern __declspec(dllexport) int QWidget_Width(const QWidget* self);
extern __declspec(dllexport) int QWidget_Height(const QWidget* self);
extern __declspec(dllexport) QRect* QWidget_Rect(const QWidget* self);
extern __declspec(dllexport) QRect* QWidget_ChildrenRect(const QWidget* self);
extern __declspec(dllexport) QRegion* QWidget_ChildrenRegion(const QWidget* self);
extern __declspec(dllexport) QSize* QWidget_MinimumSize(const QWidget* self);
extern __declspec(dllexport) QSize* QWidget_MaximumSize(const QWidget* self);
extern __declspec(dllexport) int QWidget_MinimumWidth(const QWidget* self);
extern __declspec(dllexport) int QWidget_MinimumHeight(const QWidget* self);
extern __declspec(dllexport) int QWidget_MaximumWidth(const QWidget* self);
extern __declspec(dllexport) int QWidget_MaximumHeight(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetMinimumSize(QWidget* self, QSize* minimumSize);
extern __declspec(dllexport) void QWidget_SetMinimumSize2(QWidget* self, int minw, int minh);
extern __declspec(dllexport) void QWidget_SetMaximumSize(QWidget* self, QSize* maximumSize);
extern __declspec(dllexport) void QWidget_SetMaximumSize2(QWidget* self, int maxw, int maxh);
extern __declspec(dllexport) void QWidget_SetMinimumWidth(QWidget* self, int minw);
extern __declspec(dllexport) void QWidget_SetMinimumHeight(QWidget* self, int minh);
extern __declspec(dllexport) void QWidget_SetMaximumWidth(QWidget* self, int maxw);
extern __declspec(dllexport) void QWidget_SetMaximumHeight(QWidget* self, int maxh);
extern __declspec(dllexport) QSize* QWidget_SizeIncrement(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetSizeIncrement(QWidget* self, QSize* sizeIncrement);
extern __declspec(dllexport) void QWidget_SetSizeIncrement2(QWidget* self, int w, int h);
extern __declspec(dllexport) QSize* QWidget_BaseSize(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetBaseSize(QWidget* self, QSize* baseSize);
extern __declspec(dllexport) void QWidget_SetBaseSize2(QWidget* self, int basew, int baseh);
extern __declspec(dllexport) void QWidget_SetFixedSize(QWidget* self, QSize* fixedSize);
extern __declspec(dllexport) void QWidget_SetFixedSize2(QWidget* self, int w, int h);
extern __declspec(dllexport) void QWidget_SetFixedWidth(QWidget* self, int w);
extern __declspec(dllexport) void QWidget_SetFixedHeight(QWidget* self, int h);
extern __declspec(dllexport) QPointF* QWidget_MapToGlobal(const QWidget* self, QPointF* param1);
extern __declspec(dllexport) QPoint* QWidget_MapToGlobalWithQPoint(const QWidget* self, QPoint* param1);
extern __declspec(dllexport) QPointF* QWidget_MapFromGlobal(const QWidget* self, QPointF* param1);
extern __declspec(dllexport) QPoint* QWidget_MapFromGlobalWithQPoint(const QWidget* self, QPoint* param1);
extern __declspec(dllexport) QPointF* QWidget_MapToParent(const QWidget* self, QPointF* param1);
extern __declspec(dllexport) QPoint* QWidget_MapToParentWithQPoint(const QWidget* self, QPoint* param1);
extern __declspec(dllexport) QPointF* QWidget_MapFromParent(const QWidget* self, QPointF* param1);
extern __declspec(dllexport) QPoint* QWidget_MapFromParentWithQPoint(const QWidget* self, QPoint* param1);
extern __declspec(dllexport) QPointF* QWidget_MapTo(const QWidget* self, QWidget* param1, QPointF* param2);
extern __declspec(dllexport) QPoint* QWidget_MapTo2(const QWidget* self, QWidget* param1, QPoint* param2);
extern __declspec(dllexport) QPointF* QWidget_MapFrom(const QWidget* self, QWidget* param1, QPointF* param2);
extern __declspec(dllexport) QPoint* QWidget_MapFrom2(const QWidget* self, QWidget* param1, QPoint* param2);
extern __declspec(dllexport) QWidget* QWidget_Window(const QWidget* self);
extern __declspec(dllexport) QWidget* QWidget_NativeParentWidget(const QWidget* self);
extern __declspec(dllexport) QWidget* QWidget_TopLevelWidget(const QWidget* self);
extern __declspec(dllexport) QPalette* QWidget_Palette(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetPalette(QWidget* self, QPalette* palette);
extern __declspec(dllexport) void QWidget_SetBackgroundRole(QWidget* self, int backgroundRole);
extern __declspec(dllexport) int QWidget_BackgroundRole(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetForegroundRole(QWidget* self, int foregroundRole);
extern __declspec(dllexport) int QWidget_ForegroundRole(const QWidget* self);
extern __declspec(dllexport) QFont* QWidget_Font(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetFont(QWidget* self, QFont* font);
extern __declspec(dllexport) QFontMetrics* QWidget_FontMetrics(const QWidget* self);
extern __declspec(dllexport) QFontInfo* QWidget_FontInfo(const QWidget* self);
extern __declspec(dllexport) QCursor* QWidget_Cursor(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetCursor(QWidget* self, QCursor* cursor);
extern __declspec(dllexport) void QWidget_UnsetCursor(QWidget* self);
extern __declspec(dllexport) void QWidget_SetMouseTracking(QWidget* self, bool enable);
extern __declspec(dllexport) bool QWidget_HasMouseTracking(const QWidget* self);
extern __declspec(dllexport) bool QWidget_UnderMouse(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetTabletTracking(QWidget* self, bool enable);
extern __declspec(dllexport) bool QWidget_HasTabletTracking(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetMask(QWidget* self, QBitmap* mask);
extern __declspec(dllexport) void QWidget_SetMaskWithMask(QWidget* self, QRegion* mask);
extern __declspec(dllexport) QRegion* QWidget_Mask(const QWidget* self);
extern __declspec(dllexport) void QWidget_ClearMask(QWidget* self);
extern __declspec(dllexport) void QWidget_Render(QWidget* self, QPaintDevice* target);
extern __declspec(dllexport) void QWidget_RenderWithPainter(QWidget* self, QPainter* painter);
extern __declspec(dllexport) QPixmap* QWidget_Grab(QWidget* self);
extern __declspec(dllexport) QGraphicsEffect* QWidget_GraphicsEffect(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetGraphicsEffect(QWidget* self, QGraphicsEffect* effect);
extern __declspec(dllexport) void QWidget_GrabGesture(QWidget* self, int typeVal);
extern __declspec(dllexport) void QWidget_UngrabGesture(QWidget* self, int typeVal);
extern __declspec(dllexport) void QWidget_SetWindowTitle(QWidget* self, struct miqt_string windowTitle);
extern __declspec(dllexport) void QWidget_SetStyleSheet(QWidget* self, struct miqt_string styleSheet);
extern __declspec(dllexport) struct miqt_string QWidget_StyleSheet(const QWidget* self);
extern __declspec(dllexport) struct miqt_string QWidget_WindowTitle(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetWindowIcon(QWidget* self, QIcon* icon);
extern __declspec(dllexport) QIcon* QWidget_WindowIcon(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetWindowIconText(QWidget* self, struct miqt_string windowIconText);
extern __declspec(dllexport) struct miqt_string QWidget_WindowIconText(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetWindowRole(QWidget* self, struct miqt_string windowRole);
extern __declspec(dllexport) struct miqt_string QWidget_WindowRole(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetWindowFilePath(QWidget* self, struct miqt_string filePath);
extern __declspec(dllexport) struct miqt_string QWidget_WindowFilePath(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetWindowOpacity(QWidget* self, double level);
extern __declspec(dllexport) double QWidget_WindowOpacity(const QWidget* self);
extern __declspec(dllexport) bool QWidget_IsWindowModified(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetToolTip(QWidget* self, struct miqt_string toolTip);
extern __declspec(dllexport) struct miqt_string QWidget_ToolTip(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetToolTipDuration(QWidget* self, int msec);
extern __declspec(dllexport) int QWidget_ToolTipDuration(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetStatusTip(QWidget* self, struct miqt_string statusTip);
extern __declspec(dllexport) struct miqt_string QWidget_StatusTip(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetWhatsThis(QWidget* self, struct miqt_string whatsThis);
extern __declspec(dllexport) struct miqt_string QWidget_WhatsThis(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetLayoutDirection(QWidget* self, int direction);
extern __declspec(dllexport) int QWidget_LayoutDirection(const QWidget* self);
extern __declspec(dllexport) void QWidget_UnsetLayoutDirection(QWidget* self);
extern __declspec(dllexport) void QWidget_SetLocale(QWidget* self, QLocale* locale);
extern __declspec(dllexport) QLocale* QWidget_Locale(const QWidget* self);
extern __declspec(dllexport) void QWidget_UnsetLocale(QWidget* self);
extern __declspec(dllexport) bool QWidget_IsRightToLeft(const QWidget* self);
extern __declspec(dllexport) bool QWidget_IsLeftToRight(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetFocus(QWidget* self);
extern __declspec(dllexport) bool QWidget_IsActiveWindow(const QWidget* self);
extern __declspec(dllexport) void QWidget_ActivateWindow(QWidget* self);
extern __declspec(dllexport) void QWidget_ClearFocus(QWidget* self);
extern __declspec(dllexport) void QWidget_SetFocusWithReason(QWidget* self, int reason);
extern __declspec(dllexport) int QWidget_FocusPolicy(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetFocusPolicy(QWidget* self, int policy);
extern __declspec(dllexport) bool QWidget_HasFocus(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetTabOrder(QWidget* param1, QWidget* param2);
extern __declspec(dllexport) void QWidget_SetFocusProxy(QWidget* self, QWidget* focusProxy);
extern __declspec(dllexport) QWidget* QWidget_FocusProxy(const QWidget* self);
extern __declspec(dllexport) int QWidget_ContextMenuPolicy(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetContextMenuPolicy(QWidget* self, int policy);
extern __declspec(dllexport) void QWidget_GrabMouse(QWidget* self);
extern __declspec(dllexport) void QWidget_GrabMouseWithQCursor(QWidget* self, QCursor* param1);
extern __declspec(dllexport) void QWidget_ReleaseMouse(QWidget* self);
extern __declspec(dllexport) void QWidget_GrabKeyboard(QWidget* self);
extern __declspec(dllexport) void QWidget_ReleaseKeyboard(QWidget* self);
extern __declspec(dllexport) int QWidget_GrabShortcut(QWidget* self, QKeySequence* key);
extern __declspec(dllexport) void QWidget_ReleaseShortcut(QWidget* self, int id);
extern __declspec(dllexport) void QWidget_SetShortcutEnabled(QWidget* self, int id);
extern __declspec(dllexport) void QWidget_SetShortcutAutoRepeat(QWidget* self, int id);
extern __declspec(dllexport) QWidget* QWidget_MouseGrabber();
extern __declspec(dllexport) QWidget* QWidget_KeyboardGrabber();
extern __declspec(dllexport) bool QWidget_UpdatesEnabled(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetUpdatesEnabled(QWidget* self, bool enable);
extern __declspec(dllexport) QGraphicsProxyWidget* QWidget_GraphicsProxyWidget(const QWidget* self);
extern __declspec(dllexport) void QWidget_Update(QWidget* self);
extern __declspec(dllexport) void QWidget_Repaint(QWidget* self);
extern __declspec(dllexport) void QWidget_Update2(QWidget* self, int x, int y, int w, int h);
extern __declspec(dllexport) void QWidget_UpdateWithQRect(QWidget* self, QRect* param1);
extern __declspec(dllexport) void QWidget_UpdateWithQRegion(QWidget* self, QRegion* param1);
extern __declspec(dllexport) void QWidget_Repaint2(QWidget* self, int x, int y, int w, int h);
extern __declspec(dllexport) void QWidget_RepaintWithQRect(QWidget* self, QRect* param1);
extern __declspec(dllexport) void QWidget_RepaintWithQRegion(QWidget* self, QRegion* param1);
extern __declspec(dllexport) void QWidget_SetVisible(QWidget* self, bool visible);
extern __declspec(dllexport) void QWidget_SetHidden(QWidget* self, bool hidden);
extern __declspec(dllexport) void QWidget_Show(QWidget* self);
extern __declspec(dllexport) void QWidget_Hide(QWidget* self);
extern __declspec(dllexport) void QWidget_ShowMinimized(QWidget* self);
extern __declspec(dllexport) void QWidget_ShowMaximized(QWidget* self);
extern __declspec(dllexport) void QWidget_ShowFullScreen(QWidget* self);
extern __declspec(dllexport) void QWidget_ShowNormal(QWidget* self);
extern __declspec(dllexport) bool QWidget_Close(QWidget* self);
extern __declspec(dllexport) void QWidget_Raise(QWidget* self);
extern __declspec(dllexport) void QWidget_Lower(QWidget* self);
extern __declspec(dllexport) void QWidget_StackUnder(QWidget* self, QWidget* param1);
extern __declspec(dllexport) void QWidget_Move(QWidget* self, int x, int y);
extern __declspec(dllexport) void QWidget_MoveWithQPoint(QWidget* self, QPoint* param1);
extern __declspec(dllexport) void QWidget_Resize(QWidget* self, int w, int h);
extern __declspec(dllexport) void QWidget_ResizeWithQSize(QWidget* self, QSize* param1);
extern __declspec(dllexport) void QWidget_SetGeometry(QWidget* self, int x, int y, int w, int h);
extern __declspec(dllexport) void QWidget_SetGeometryWithGeometry(QWidget* self, QRect* geometry);
extern __declspec(dllexport) struct miqt_string QWidget_SaveGeometry(const QWidget* self);
extern __declspec(dllexport) bool QWidget_RestoreGeometry(QWidget* self, struct miqt_string geometry);
extern __declspec(dllexport) void QWidget_AdjustSize(QWidget* self);
extern __declspec(dllexport) bool QWidget_IsVisible(const QWidget* self);
extern __declspec(dllexport) bool QWidget_IsVisibleTo(const QWidget* self, QWidget* param1);
extern __declspec(dllexport) bool QWidget_IsHidden(const QWidget* self);
extern __declspec(dllexport) bool QWidget_IsMinimized(const QWidget* self);
extern __declspec(dllexport) bool QWidget_IsMaximized(const QWidget* self);
extern __declspec(dllexport) bool QWidget_IsFullScreen(const QWidget* self);
extern __declspec(dllexport) int QWidget_WindowState(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetWindowState(QWidget* self, int state);
extern __declspec(dllexport) void QWidget_OverrideWindowState(QWidget* self, int state);
extern __declspec(dllexport) QSize* QWidget_SizeHint(const QWidget* self);
extern __declspec(dllexport) QSize* QWidget_MinimumSizeHint(const QWidget* self);
extern __declspec(dllexport) QSizePolicy* QWidget_SizePolicy(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetSizePolicy(QWidget* self, QSizePolicy* sizePolicy);
extern __declspec(dllexport) void QWidget_SetSizePolicy2(QWidget* self, int horizontal, int vertical);
extern __declspec(dllexport) int QWidget_HeightForWidth(const QWidget* self, int param1);
extern __declspec(dllexport) bool QWidget_HasHeightForWidth(const QWidget* self);
extern __declspec(dllexport) QRegion* QWidget_VisibleRegion(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetContentsMargins(QWidget* self, int left, int top, int right, int bottom);
extern __declspec(dllexport) void QWidget_SetContentsMarginsWithMargins(QWidget* self, QMargins* margins);
extern __declspec(dllexport) QMargins* QWidget_ContentsMargins(const QWidget* self);
extern __declspec(dllexport) QRect* QWidget_ContentsRect(const QWidget* self);
extern __declspec(dllexport) QLayout* QWidget_Layout(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetLayout(QWidget* self, QLayout* layout);
extern __declspec(dllexport) void QWidget_UpdateGeometry(QWidget* self);
extern __declspec(dllexport) void QWidget_SetParent(QWidget* self, QWidget* parent);
extern __declspec(dllexport) void QWidget_SetParent2(QWidget* self, QWidget* parent, int f);
extern __declspec(dllexport) void QWidget_Scroll(QWidget* self, int dx, int dy);
extern __declspec(dllexport) void QWidget_Scroll2(QWidget* self, int dx, int dy, QRect* param3);
extern __declspec(dllexport) QWidget* QWidget_FocusWidget(const QWidget* self);
extern __declspec(dllexport) QWidget* QWidget_NextInFocusChain(const QWidget* self);
extern __declspec(dllexport) QWidget* QWidget_PreviousInFocusChain(const QWidget* self);
extern __declspec(dllexport) bool QWidget_AcceptDrops(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetAcceptDrops(QWidget* self, bool on);
extern __declspec(dllexport) void QWidget_AddAction(QWidget* self, QAction* action);
extern __declspec(dllexport) void QWidget_AddActions(QWidget* self, struct miqt_array /* of QAction* */  actions);
extern __declspec(dllexport) void QWidget_InsertActions(QWidget* self, QAction* before, struct miqt_array /* of QAction* */  actions);
extern __declspec(dllexport) void QWidget_InsertAction(QWidget* self, QAction* before, QAction* action);
extern __declspec(dllexport) void QWidget_RemoveAction(QWidget* self, QAction* action);
extern __declspec(dllexport) struct miqt_array /* of QAction* */  QWidget_Actions(const QWidget* self);
extern __declspec(dllexport) QAction* QWidget_AddActionWithText(QWidget* self, struct miqt_string text);
extern __declspec(dllexport) QAction* QWidget_AddAction2(QWidget* self, QIcon* icon, struct miqt_string text);
extern __declspec(dllexport) QAction* QWidget_AddAction3(QWidget* self, struct miqt_string text, QKeySequence* shortcut);
extern __declspec(dllexport) QAction* QWidget_AddAction4(QWidget* self, QIcon* icon, struct miqt_string text, QKeySequence* shortcut);
extern __declspec(dllexport) QWidget* QWidget_ParentWidget(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetWindowFlags(QWidget* self, int typeVal);
extern __declspec(dllexport) int QWidget_WindowFlags(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetWindowFlag(QWidget* self, int param1);
extern __declspec(dllexport) void QWidget_OverrideWindowFlags(QWidget* self, int typeVal);
extern __declspec(dllexport) int QWidget_WindowType(const QWidget* self);
extern __declspec(dllexport) QWidget* QWidget_Find(uintptr_t param1);
extern __declspec(dllexport) QWidget* QWidget_ChildAt(const QWidget* self, int x, int y);
extern __declspec(dllexport) QWidget* QWidget_ChildAtWithQPoint(const QWidget* self, QPoint* p);
extern __declspec(dllexport) QWidget* QWidget_ChildAtWithQPointF(const QWidget* self, QPointF* p);
extern __declspec(dllexport) void QWidget_SetAttribute(QWidget* self, int param1);
extern __declspec(dllexport) bool QWidget_TestAttribute(const QWidget* self, int param1);
extern __declspec(dllexport) QPaintEngine* QWidget_PaintEngine(const QWidget* self);
extern __declspec(dllexport) void QWidget_EnsurePolished(const QWidget* self);
extern __declspec(dllexport) bool QWidget_IsAncestorOf(const QWidget* self, QWidget* child);
extern __declspec(dllexport) bool QWidget_AutoFillBackground(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetAutoFillBackground(QWidget* self, bool enabled);
extern __declspec(dllexport) QBackingStore* QWidget_BackingStore(const QWidget* self);
extern __declspec(dllexport) QWindow* QWidget_WindowHandle(const QWidget* self);
extern __declspec(dllexport) QScreen* QWidget_Screen(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetScreen(QWidget* self, QScreen* screen);
extern __declspec(dllexport) QWidget* QWidget_CreateWindowContainer(QWindow* window);
extern __declspec(dllexport) void QWidget_WindowTitleChanged(QWidget* self, struct miqt_string title);
void QWidget_connect_WindowTitleChanged(QWidget* self, intptr_t slot);
extern __declspec(dllexport) void QWidget_WindowIconChanged(QWidget* self, QIcon* icon);
void QWidget_connect_WindowIconChanged(QWidget* self, intptr_t slot);
extern __declspec(dllexport) void QWidget_WindowIconTextChanged(QWidget* self, struct miqt_string iconText);
void QWidget_connect_WindowIconTextChanged(QWidget* self, intptr_t slot);
extern __declspec(dllexport) void QWidget_CustomContextMenuRequested(QWidget* self, QPoint* pos);
void QWidget_connect_CustomContextMenuRequested(QWidget* self, intptr_t slot);
extern __declspec(dllexport) bool QWidget_Event(QWidget* self, QEvent* event);
extern __declspec(dllexport) void QWidget_MousePressEvent(QWidget* self, QMouseEvent* event);
extern __declspec(dllexport) void QWidget_MouseReleaseEvent(QWidget* self, QMouseEvent* event);
extern __declspec(dllexport) void QWidget_MouseDoubleClickEvent(QWidget* self, QMouseEvent* event);
extern __declspec(dllexport) void QWidget_MouseMoveEvent(QWidget* self, QMouseEvent* event);
extern __declspec(dllexport) void QWidget_WheelEvent(QWidget* self, QWheelEvent* event);
extern __declspec(dllexport) void QWidget_KeyPressEvent(QWidget* self, QKeyEvent* event);
extern __declspec(dllexport) void QWidget_KeyReleaseEvent(QWidget* self, QKeyEvent* event);
extern __declspec(dllexport) void QWidget_FocusInEvent(QWidget* self, QFocusEvent* event);
extern __declspec(dllexport) void QWidget_FocusOutEvent(QWidget* self, QFocusEvent* event);
extern __declspec(dllexport) void QWidget_EnterEvent(QWidget* self, QEnterEvent* event);
extern __declspec(dllexport) void QWidget_LeaveEvent(QWidget* self, QEvent* event);
extern __declspec(dllexport) void QWidget_PaintEvent(QWidget* self, QPaintEvent* event);
extern __declspec(dllexport) void QWidget_MoveEvent(QWidget* self, QMoveEvent* event);
extern __declspec(dllexport) void QWidget_ResizeEvent(QWidget* self, QResizeEvent* event);
extern __declspec(dllexport) void QWidget_CloseEvent(QWidget* self, QCloseEvent* event);
extern __declspec(dllexport) void QWidget_ContextMenuEvent(QWidget* self, QContextMenuEvent* event);
extern __declspec(dllexport) void QWidget_TabletEvent(QWidget* self, QTabletEvent* event);
extern __declspec(dllexport) void QWidget_ActionEvent(QWidget* self, QActionEvent* event);
extern __declspec(dllexport) void QWidget_DragEnterEvent(QWidget* self, QDragEnterEvent* event);
extern __declspec(dllexport) void QWidget_DragMoveEvent(QWidget* self, QDragMoveEvent* event);
extern __declspec(dllexport) void QWidget_DragLeaveEvent(QWidget* self, QDragLeaveEvent* event);
extern __declspec(dllexport) void QWidget_DropEvent(QWidget* self, QDropEvent* event);
extern __declspec(dllexport) void QWidget_ShowEvent(QWidget* self, QShowEvent* event);
extern __declspec(dllexport) void QWidget_HideEvent(QWidget* self, QHideEvent* event);
extern __declspec(dllexport) bool QWidget_NativeEvent(QWidget* self, struct miqt_string eventType, void* message, intptr_t* result);
extern __declspec(dllexport) void QWidget_ChangeEvent(QWidget* self, QEvent* param1);
extern __declspec(dllexport) int QWidget_Metric(const QWidget* self, PaintDeviceMetric param1);
extern __declspec(dllexport) void QWidget_InitPainter(const QWidget* self, QPainter* painter);
extern __declspec(dllexport) QPaintDevice* QWidget_Redirected(const QWidget* self, QPoint* offset);
extern __declspec(dllexport) QPainter* QWidget_SharedPainter(const QWidget* self);
extern __declspec(dllexport) void QWidget_InputMethodEvent(QWidget* self, QInputMethodEvent* param1);
extern __declspec(dllexport) QVariant* QWidget_InputMethodQuery(const QWidget* self, int param1);
extern __declspec(dllexport) int QWidget_InputMethodHints(const QWidget* self);
extern __declspec(dllexport) void QWidget_SetInputMethodHints(QWidget* self, int hints);
extern __declspec(dllexport) bool QWidget_FocusNextPrevChild(QWidget* self, bool next);
extern __declspec(dllexport) struct miqt_string QWidget_Tr2(const char* s, const char* c);
extern __declspec(dllexport) struct miqt_string QWidget_Tr3(const char* s, const char* c, int n);
extern __declspec(dllexport) void QWidget_Render2(QWidget* self, QPaintDevice* target, QPoint* targetOffset);
extern __declspec(dllexport) void QWidget_Render3(QWidget* self, QPaintDevice* target, QPoint* targetOffset, QRegion* sourceRegion);
extern __declspec(dllexport) void QWidget_Render4(QWidget* self, QPaintDevice* target, QPoint* targetOffset, QRegion* sourceRegion, RenderFlags renderFlags);
extern __declspec(dllexport) void QWidget_Render22(QWidget* self, QPainter* painter, QPoint* targetOffset);
extern __declspec(dllexport) void QWidget_Render32(QWidget* self, QPainter* painter, QPoint* targetOffset, QRegion* sourceRegion);
extern __declspec(dllexport) void QWidget_Render42(QWidget* self, QPainter* painter, QPoint* targetOffset, QRegion* sourceRegion, RenderFlags renderFlags);
extern __declspec(dllexport) QPixmap* QWidget_Grab1(QWidget* self, QRect* rectangle);
extern __declspec(dllexport) void QWidget_GrabGesture2(QWidget* self, int typeVal, int flags);
extern __declspec(dllexport) int QWidget_GrabShortcut2(QWidget* self, QKeySequence* key, int context);
extern __declspec(dllexport) void QWidget_SetShortcutEnabled2(QWidget* self, int id, bool enable);
extern __declspec(dllexport) void QWidget_SetShortcutAutoRepeat2(QWidget* self, int id, bool enable);
extern __declspec(dllexport) void QWidget_SetWindowFlag2(QWidget* self, int param1, bool on);
extern __declspec(dllexport) void QWidget_SetAttribute2(QWidget* self, int param1, bool on);
extern __declspec(dllexport) QWidget* QWidget_CreateWindowContainer2(QWindow* window, QWidget* parent);
extern __declspec(dllexport) QWidget* QWidget_CreateWindowContainer3(QWindow* window, QWidget* parent, int flags);
extern __declspec(dllexport) void QWidget_override_virtual_DevType(void* self, intptr_t slot);
int QWidget_virtualbase_DevType(const void* self);
extern __declspec(dllexport) void QWidget_override_virtual_SetVisible(void* self, intptr_t slot);
void QWidget_virtualbase_SetVisible(void* self, bool visible);
extern __declspec(dllexport) void QWidget_override_virtual_SizeHint(void* self, intptr_t slot);
QSize* QWidget_virtualbase_SizeHint(const void* self);
extern __declspec(dllexport) void QWidget_override_virtual_MinimumSizeHint(void* self, intptr_t slot);
QSize* QWidget_virtualbase_MinimumSizeHint(const void* self);
extern __declspec(dllexport) void QWidget_override_virtual_HeightForWidth(void* self, intptr_t slot);
int QWidget_virtualbase_HeightForWidth(const void* self, int param1);
extern __declspec(dllexport) void QWidget_override_virtual_HasHeightForWidth(void* self, intptr_t slot);
bool QWidget_virtualbase_HasHeightForWidth(const void* self);
extern __declspec(dllexport) void QWidget_override_virtual_PaintEngine(void* self, intptr_t slot);
QPaintEngine* QWidget_virtualbase_PaintEngine(const void* self);
extern __declspec(dllexport) void QWidget_override_virtual_Event(void* self, intptr_t slot);
bool QWidget_virtualbase_Event(void* self, QEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_MousePressEvent(void* self, intptr_t slot);
void QWidget_virtualbase_MousePressEvent(void* self, QMouseEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_MouseReleaseEvent(void* self, intptr_t slot);
void QWidget_virtualbase_MouseReleaseEvent(void* self, QMouseEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_MouseDoubleClickEvent(void* self, intptr_t slot);
void QWidget_virtualbase_MouseDoubleClickEvent(void* self, QMouseEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_MouseMoveEvent(void* self, intptr_t slot);
void QWidget_virtualbase_MouseMoveEvent(void* self, QMouseEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_WheelEvent(void* self, intptr_t slot);
void QWidget_virtualbase_WheelEvent(void* self, QWheelEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_KeyPressEvent(void* self, intptr_t slot);
void QWidget_virtualbase_KeyPressEvent(void* self, QKeyEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_KeyReleaseEvent(void* self, intptr_t slot);
void QWidget_virtualbase_KeyReleaseEvent(void* self, QKeyEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_FocusInEvent(void* self, intptr_t slot);
void QWidget_virtualbase_FocusInEvent(void* self, QFocusEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_FocusOutEvent(void* self, intptr_t slot);
void QWidget_virtualbase_FocusOutEvent(void* self, QFocusEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_EnterEvent(void* self, intptr_t slot);
void QWidget_virtualbase_EnterEvent(void* self, QEnterEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_LeaveEvent(void* self, intptr_t slot);
void QWidget_virtualbase_LeaveEvent(void* self, QEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_PaintEvent(void* self, intptr_t slot);
void QWidget_virtualbase_PaintEvent(void* self, QPaintEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_MoveEvent(void* self, intptr_t slot);
void QWidget_virtualbase_MoveEvent(void* self, QMoveEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_ResizeEvent(void* self, intptr_t slot);
void QWidget_virtualbase_ResizeEvent(void* self, QResizeEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_CloseEvent(void* self, intptr_t slot);
void QWidget_virtualbase_CloseEvent(void* self, QCloseEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_ContextMenuEvent(void* self, intptr_t slot);
void QWidget_virtualbase_ContextMenuEvent(void* self, QContextMenuEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_TabletEvent(void* self, intptr_t slot);
void QWidget_virtualbase_TabletEvent(void* self, QTabletEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_ActionEvent(void* self, intptr_t slot);
void QWidget_virtualbase_ActionEvent(void* self, QActionEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_DragEnterEvent(void* self, intptr_t slot);
void QWidget_virtualbase_DragEnterEvent(void* self, QDragEnterEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_DragMoveEvent(void* self, intptr_t slot);
void QWidget_virtualbase_DragMoveEvent(void* self, QDragMoveEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_DragLeaveEvent(void* self, intptr_t slot);
void QWidget_virtualbase_DragLeaveEvent(void* self, QDragLeaveEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_DropEvent(void* self, intptr_t slot);
void QWidget_virtualbase_DropEvent(void* self, QDropEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_ShowEvent(void* self, intptr_t slot);
void QWidget_virtualbase_ShowEvent(void* self, QShowEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_HideEvent(void* self, intptr_t slot);
void QWidget_virtualbase_HideEvent(void* self, QHideEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_NativeEvent(void* self, intptr_t slot);
bool QWidget_virtualbase_NativeEvent(void* self, struct miqt_string eventType, void* message, intptr_t* result);
extern __declspec(dllexport) void QWidget_override_virtual_ChangeEvent(void* self, intptr_t slot);
void QWidget_virtualbase_ChangeEvent(void* self, QEvent* param1);
extern __declspec(dllexport) void QWidget_override_virtual_Metric(void* self, intptr_t slot);
int QWidget_virtualbase_Metric(const void* self, PaintDeviceMetric param1);
extern __declspec(dllexport) void QWidget_override_virtual_InitPainter(void* self, intptr_t slot);
void QWidget_virtualbase_InitPainter(const void* self, QPainter* painter);
extern __declspec(dllexport) void QWidget_override_virtual_Redirected(void* self, intptr_t slot);
QPaintDevice* QWidget_virtualbase_Redirected(const void* self, QPoint* offset);
extern __declspec(dllexport) void QWidget_override_virtual_SharedPainter(void* self, intptr_t slot);
QPainter* QWidget_virtualbase_SharedPainter(const void* self);
extern __declspec(dllexport) void QWidget_override_virtual_InputMethodEvent(void* self, intptr_t slot);
void QWidget_virtualbase_InputMethodEvent(void* self, QInputMethodEvent* param1);
extern __declspec(dllexport) void QWidget_override_virtual_InputMethodQuery(void* self, intptr_t slot);
QVariant* QWidget_virtualbase_InputMethodQuery(const void* self, int param1);
extern __declspec(dllexport) void QWidget_override_virtual_FocusNextPrevChild(void* self, intptr_t slot);
bool QWidget_virtualbase_FocusNextPrevChild(void* self, bool next);
extern __declspec(dllexport) void QWidget_override_virtual_EventFilter(void* self, intptr_t slot);
bool QWidget_virtualbase_EventFilter(void* self, QObject* watched, QEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_TimerEvent(void* self, intptr_t slot);
void QWidget_virtualbase_TimerEvent(void* self, QTimerEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_ChildEvent(void* self, intptr_t slot);
void QWidget_virtualbase_ChildEvent(void* self, QChildEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_CustomEvent(void* self, intptr_t slot);
void QWidget_virtualbase_CustomEvent(void* self, QEvent* event);
extern __declspec(dllexport) void QWidget_override_virtual_ConnectNotify(void* self, intptr_t slot);
void QWidget_virtualbase_ConnectNotify(void* self, QMetaMethod* signal);
extern __declspec(dllexport) void QWidget_override_virtual_DisconnectNotify(void* self, intptr_t slot);
void QWidget_virtualbase_DisconnectNotify(void* self, QMetaMethod* signal);
extern __declspec(dllexport) void QWidget_Delete(QWidget* self, bool isSubclass);

#ifdef __cplusplus
} /* extern C */
#endif 

#endif
