#pragma once
#ifndef MIQT_QT_GEN_QWINDOW_H
#define MIQT_QT_GEN_QWINDOW_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "../libmiqt/libmiqt.h"
extern "C" {
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QCursor QCursor;
typedef struct QEvent QEvent;
typedef struct QExposeEvent QExposeEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QIcon QIcon;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMargins QMargins;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPoint QPoint;
typedef struct QPointF QPointF;
typedef struct QRect QRect;
typedef struct QRegion QRegion;
typedef struct QResizeEvent QResizeEvent;
typedef struct QScreen QScreen;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QSurface QSurface;
typedef struct QSurfaceFormat QSurfaceFormat;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QTouchEvent QTouchEvent;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWindow QWindow;
typedef struct _GUID _GUID;
typedef struct type_info type_info;

extern __declspec(dllexport) void _GUID_Delete(_GUID* self, bool isSubclass);

extern __declspec(dllexport) void type_info_Delete(type_info* self, bool isSubclass);

extern __declspec(dllexport) QWindow* QWindow_new();
extern __declspec(dllexport) QWindow* QWindow_new2(QWindow* parent);
extern __declspec(dllexport) QWindow* QWindow_new3(QScreen* screen);
extern __declspec(dllexport) void QWindow_virtbase(QWindow* src, QObject** outptr_QObject, QSurface** outptr_QSurface);
extern __declspec(dllexport) QMetaObject* QWindow_MetaObject(const QWindow* self);
extern __declspec(dllexport) void* QWindow_Metacast(QWindow* self, const char* param1);
extern __declspec(dllexport) struct miqt_string QWindow_Tr(const char* s);
extern __declspec(dllexport) void QWindow_SetSurfaceType(QWindow* self, SurfaceType surfaceType);
extern __declspec(dllexport) SurfaceType QWindow_SurfaceType(const QWindow* self);
extern __declspec(dllexport) bool QWindow_IsVisible(const QWindow* self);
extern __declspec(dllexport) Visibility QWindow_Visibility(const QWindow* self);
extern __declspec(dllexport) void QWindow_SetVisibility(QWindow* self, Visibility v);
extern __declspec(dllexport) void QWindow_Create(QWindow* self);
extern __declspec(dllexport) uintptr_t QWindow_WinId(const QWindow* self);
extern __declspec(dllexport) QWindow* QWindow_Parent(const QWindow* self);
extern __declspec(dllexport) void QWindow_SetParent(QWindow* self, QWindow* parent);
extern __declspec(dllexport) bool QWindow_IsTopLevel(const QWindow* self);
extern __declspec(dllexport) bool QWindow_IsModal(const QWindow* self);
extern __declspec(dllexport) int QWindow_Modality(const QWindow* self);
extern __declspec(dllexport) void QWindow_SetModality(QWindow* self, int modality);
extern __declspec(dllexport) void QWindow_SetFormat(QWindow* self, QSurfaceFormat* format);
extern __declspec(dllexport) QSurfaceFormat* QWindow_Format(const QWindow* self);
extern __declspec(dllexport) QSurfaceFormat* QWindow_RequestedFormat(const QWindow* self);
extern __declspec(dllexport) void QWindow_SetFlags(QWindow* self, int flags);
extern __declspec(dllexport) int QWindow_Flags(const QWindow* self);
extern __declspec(dllexport) void QWindow_SetFlag(QWindow* self, int param1);
extern __declspec(dllexport) int QWindow_Type(const QWindow* self);
extern __declspec(dllexport) struct miqt_string QWindow_Title(const QWindow* self);
extern __declspec(dllexport) void QWindow_SetOpacity(QWindow* self, double level);
extern __declspec(dllexport) double QWindow_Opacity(const QWindow* self);
extern __declspec(dllexport) void QWindow_SetMask(QWindow* self, QRegion* region);
extern __declspec(dllexport) QRegion* QWindow_Mask(const QWindow* self);
extern __declspec(dllexport) bool QWindow_IsActive(const QWindow* self);
extern __declspec(dllexport) void QWindow_ReportContentOrientationChange(QWindow* self, int orientation);
extern __declspec(dllexport) int QWindow_ContentOrientation(const QWindow* self);
extern __declspec(dllexport) double QWindow_DevicePixelRatio(const QWindow* self);
extern __declspec(dllexport) int QWindow_WindowState(const QWindow* self);
extern __declspec(dllexport) int QWindow_WindowStates(const QWindow* self);
extern __declspec(dllexport) void QWindow_SetWindowState(QWindow* self, int state);
extern __declspec(dllexport) void QWindow_SetWindowStates(QWindow* self, int states);
extern __declspec(dllexport) void QWindow_SetTransientParent(QWindow* self, QWindow* parent);
extern __declspec(dllexport) QWindow* QWindow_TransientParent(const QWindow* self);
extern __declspec(dllexport) bool QWindow_IsAncestorOf(const QWindow* self, QWindow* child);
extern __declspec(dllexport) bool QWindow_IsExposed(const QWindow* self);
extern __declspec(dllexport) int QWindow_MinimumWidth(const QWindow* self);
extern __declspec(dllexport) int QWindow_MinimumHeight(const QWindow* self);
extern __declspec(dllexport) int QWindow_MaximumWidth(const QWindow* self);
extern __declspec(dllexport) int QWindow_MaximumHeight(const QWindow* self);
extern __declspec(dllexport) QSize* QWindow_MinimumSize(const QWindow* self);
extern __declspec(dllexport) QSize* QWindow_MaximumSize(const QWindow* self);
extern __declspec(dllexport) QSize* QWindow_BaseSize(const QWindow* self);
extern __declspec(dllexport) QSize* QWindow_SizeIncrement(const QWindow* self);
extern __declspec(dllexport) void QWindow_SetMinimumSize(QWindow* self, QSize* size);
extern __declspec(dllexport) void QWindow_SetMaximumSize(QWindow* self, QSize* size);
extern __declspec(dllexport) void QWindow_SetBaseSize(QWindow* self, QSize* size);
extern __declspec(dllexport) void QWindow_SetSizeIncrement(QWindow* self, QSize* size);
extern __declspec(dllexport) QRect* QWindow_Geometry(const QWindow* self);
extern __declspec(dllexport) QMargins* QWindow_FrameMargins(const QWindow* self);
extern __declspec(dllexport) QRect* QWindow_FrameGeometry(const QWindow* self);
extern __declspec(dllexport) QPoint* QWindow_FramePosition(const QWindow* self);
extern __declspec(dllexport) void QWindow_SetFramePosition(QWindow* self, QPoint* point);
extern __declspec(dllexport) QMargins* QWindow_SafeAreaMargins(const QWindow* self);
extern __declspec(dllexport) int QWindow_Width(const QWindow* self);
extern __declspec(dllexport) int QWindow_Height(const QWindow* self);
extern __declspec(dllexport) int QWindow_X(const QWindow* self);
extern __declspec(dllexport) int QWindow_Y(const QWindow* self);
extern __declspec(dllexport) QSize* QWindow_Size(const QWindow* self);
extern __declspec(dllexport) QPoint* QWindow_Position(const QWindow* self);
extern __declspec(dllexport) void QWindow_SetPosition(QWindow* self, QPoint* pt);
extern __declspec(dllexport) void QWindow_SetPosition2(QWindow* self, int posx, int posy);
extern __declspec(dllexport) void QWindow_Resize(QWindow* self, QSize* newSize);
extern __declspec(dllexport) void QWindow_Resize2(QWindow* self, int w, int h);
extern __declspec(dllexport) void QWindow_SetFilePath(QWindow* self, struct miqt_string filePath);
extern __declspec(dllexport) struct miqt_string QWindow_FilePath(const QWindow* self);
extern __declspec(dllexport) void QWindow_SetIcon(QWindow* self, QIcon* icon);
extern __declspec(dllexport) QIcon* QWindow_Icon(const QWindow* self);
extern __declspec(dllexport) void QWindow_Destroy(QWindow* self);
extern __declspec(dllexport) bool QWindow_SetKeyboardGrabEnabled(QWindow* self, bool grab);
extern __declspec(dllexport) bool QWindow_SetMouseGrabEnabled(QWindow* self, bool grab);
extern __declspec(dllexport) QScreen* QWindow_Screen(const QWindow* self);
extern __declspec(dllexport) void QWindow_SetScreen(QWindow* self, QScreen* screen);
extern __declspec(dllexport) QAccessibleInterface* QWindow_AccessibleRoot(const QWindow* self);
extern __declspec(dllexport) QObject* QWindow_FocusObject(const QWindow* self);
extern __declspec(dllexport) QPointF* QWindow_MapToGlobal(const QWindow* self, QPointF* pos);
extern __declspec(dllexport) QPointF* QWindow_MapFromGlobal(const QWindow* self, QPointF* pos);
extern __declspec(dllexport) QPoint* QWindow_MapToGlobalWithPos(const QWindow* self, QPoint* pos);
extern __declspec(dllexport) QPoint* QWindow_MapFromGlobalWithPos(const QWindow* self, QPoint* pos);
extern __declspec(dllexport) QCursor* QWindow_Cursor(const QWindow* self);
extern __declspec(dllexport) void QWindow_SetCursor(QWindow* self, QCursor* cursor);
extern __declspec(dllexport) void QWindow_UnsetCursor(QWindow* self);
extern __declspec(dllexport) QWindow* QWindow_FromWinId(uintptr_t id);
extern __declspec(dllexport) void QWindow_RequestActivate(QWindow* self);
extern __declspec(dllexport) void QWindow_SetVisible(QWindow* self, bool visible);
extern __declspec(dllexport) void QWindow_Show(QWindow* self);
extern __declspec(dllexport) void QWindow_Hide(QWindow* self);
extern __declspec(dllexport) void QWindow_ShowMinimized(QWindow* self);
extern __declspec(dllexport) void QWindow_ShowMaximized(QWindow* self);
extern __declspec(dllexport) void QWindow_ShowFullScreen(QWindow* self);
extern __declspec(dllexport) void QWindow_ShowNormal(QWindow* self);
extern __declspec(dllexport) bool QWindow_Close(QWindow* self);
extern __declspec(dllexport) void QWindow_Raise(QWindow* self);
extern __declspec(dllexport) void QWindow_Lower(QWindow* self);
extern __declspec(dllexport) bool QWindow_StartSystemResize(QWindow* self, int edges);
extern __declspec(dllexport) bool QWindow_StartSystemMove(QWindow* self);
extern __declspec(dllexport) void QWindow_SetTitle(QWindow* self, struct miqt_string title);
extern __declspec(dllexport) void QWindow_SetX(QWindow* self, int arg);
extern __declspec(dllexport) void QWindow_SetY(QWindow* self, int arg);
extern __declspec(dllexport) void QWindow_SetWidth(QWindow* self, int arg);
extern __declspec(dllexport) void QWindow_SetHeight(QWindow* self, int arg);
extern __declspec(dllexport) void QWindow_SetGeometry(QWindow* self, int posx, int posy, int w, int h);
extern __declspec(dllexport) void QWindow_SetGeometryWithRect(QWindow* self, QRect* rect);
extern __declspec(dllexport) void QWindow_SetMinimumWidth(QWindow* self, int w);
extern __declspec(dllexport) void QWindow_SetMinimumHeight(QWindow* self, int h);
extern __declspec(dllexport) void QWindow_SetMaximumWidth(QWindow* self, int w);
extern __declspec(dllexport) void QWindow_SetMaximumHeight(QWindow* self, int h);
extern __declspec(dllexport) void QWindow_Alert(QWindow* self, int msec);
extern __declspec(dllexport) void QWindow_RequestUpdate(QWindow* self);
extern __declspec(dllexport) void QWindow_ScreenChanged(QWindow* self, QScreen* screen);
void QWindow_connect_ScreenChanged(QWindow* self, intptr_t slot);
extern __declspec(dllexport) void QWindow_ModalityChanged(QWindow* self, int modality);
void QWindow_connect_ModalityChanged(QWindow* self, intptr_t slot);
extern __declspec(dllexport) void QWindow_WindowStateChanged(QWindow* self, int windowState);
void QWindow_connect_WindowStateChanged(QWindow* self, intptr_t slot);
extern __declspec(dllexport) void QWindow_WindowTitleChanged(QWindow* self, struct miqt_string title);
void QWindow_connect_WindowTitleChanged(QWindow* self, intptr_t slot);
extern __declspec(dllexport) void QWindow_XChanged(QWindow* self, int arg);
void QWindow_connect_XChanged(QWindow* self, intptr_t slot);
extern __declspec(dllexport) void QWindow_YChanged(QWindow* self, int arg);
void QWindow_connect_YChanged(QWindow* self, intptr_t slot);
extern __declspec(dllexport) void QWindow_WidthChanged(QWindow* self, int arg);
void QWindow_connect_WidthChanged(QWindow* self, intptr_t slot);
extern __declspec(dllexport) void QWindow_HeightChanged(QWindow* self, int arg);
void QWindow_connect_HeightChanged(QWindow* self, intptr_t slot);
extern __declspec(dllexport) void QWindow_MinimumWidthChanged(QWindow* self, int arg);
void QWindow_connect_MinimumWidthChanged(QWindow* self, intptr_t slot);
extern __declspec(dllexport) void QWindow_MinimumHeightChanged(QWindow* self, int arg);
void QWindow_connect_MinimumHeightChanged(QWindow* self, intptr_t slot);
extern __declspec(dllexport) void QWindow_MaximumWidthChanged(QWindow* self, int arg);
void QWindow_connect_MaximumWidthChanged(QWindow* self, intptr_t slot);
extern __declspec(dllexport) void QWindow_MaximumHeightChanged(QWindow* self, int arg);
void QWindow_connect_MaximumHeightChanged(QWindow* self, intptr_t slot);
extern __declspec(dllexport) void QWindow_SafeAreaMarginsChanged(QWindow* self, QMargins* arg);
void QWindow_connect_SafeAreaMarginsChanged(QWindow* self, intptr_t slot);
extern __declspec(dllexport) void QWindow_VisibleChanged(QWindow* self, bool arg);
void QWindow_connect_VisibleChanged(QWindow* self, intptr_t slot);
extern __declspec(dllexport) void QWindow_VisibilityChanged(QWindow* self, int visibility);
void QWindow_connect_VisibilityChanged(QWindow* self, intptr_t slot);
extern __declspec(dllexport) void QWindow_ActiveChanged(QWindow* self);
void QWindow_connect_ActiveChanged(QWindow* self, intptr_t slot);
extern __declspec(dllexport) void QWindow_ContentOrientationChanged(QWindow* self, int orientation);
void QWindow_connect_ContentOrientationChanged(QWindow* self, intptr_t slot);
extern __declspec(dllexport) void QWindow_FocusObjectChanged(QWindow* self, QObject* object);
void QWindow_connect_FocusObjectChanged(QWindow* self, intptr_t slot);
extern __declspec(dllexport) void QWindow_OpacityChanged(QWindow* self, double opacity);
void QWindow_connect_OpacityChanged(QWindow* self, intptr_t slot);
extern __declspec(dllexport) void QWindow_TransientParentChanged(QWindow* self, QWindow* transientParent);
void QWindow_connect_TransientParentChanged(QWindow* self, intptr_t slot);
extern __declspec(dllexport) void QWindow_ExposeEvent(QWindow* self, QExposeEvent* param1);
extern __declspec(dllexport) void QWindow_ResizeEvent(QWindow* self, QResizeEvent* param1);
extern __declspec(dllexport) void QWindow_PaintEvent(QWindow* self, QPaintEvent* param1);
extern __declspec(dllexport) void QWindow_MoveEvent(QWindow* self, QMoveEvent* param1);
extern __declspec(dllexport) void QWindow_FocusInEvent(QWindow* self, QFocusEvent* param1);
extern __declspec(dllexport) void QWindow_FocusOutEvent(QWindow* self, QFocusEvent* param1);
extern __declspec(dllexport) void QWindow_ShowEvent(QWindow* self, QShowEvent* param1);
extern __declspec(dllexport) void QWindow_HideEvent(QWindow* self, QHideEvent* param1);
extern __declspec(dllexport) void QWindow_CloseEvent(QWindow* self, QCloseEvent* param1);
extern __declspec(dllexport) bool QWindow_Event(QWindow* self, QEvent* param1);
extern __declspec(dllexport) void QWindow_KeyPressEvent(QWindow* self, QKeyEvent* param1);
extern __declspec(dllexport) void QWindow_KeyReleaseEvent(QWindow* self, QKeyEvent* param1);
extern __declspec(dllexport) void QWindow_MousePressEvent(QWindow* self, QMouseEvent* param1);
extern __declspec(dllexport) void QWindow_MouseReleaseEvent(QWindow* self, QMouseEvent* param1);
extern __declspec(dllexport) void QWindow_MouseDoubleClickEvent(QWindow* self, QMouseEvent* param1);
extern __declspec(dllexport) void QWindow_MouseMoveEvent(QWindow* self, QMouseEvent* param1);
extern __declspec(dllexport) void QWindow_WheelEvent(QWindow* self, QWheelEvent* param1);
extern __declspec(dllexport) void QWindow_TouchEvent(QWindow* self, QTouchEvent* param1);
extern __declspec(dllexport) void QWindow_TabletEvent(QWindow* self, QTabletEvent* param1);
extern __declspec(dllexport) bool QWindow_NativeEvent(QWindow* self, struct miqt_string eventType, void* message, intptr_t* result);
extern __declspec(dllexport) struct miqt_string QWindow_Tr2(const char* s, const char* c);
extern __declspec(dllexport) struct miqt_string QWindow_Tr3(const char* s, const char* c, int n);
extern __declspec(dllexport) QWindow* QWindow_Parent1(const QWindow* self, AncestorMode mode);
extern __declspec(dllexport) void QWindow_SetFlag2(QWindow* self, int param1, bool on);
extern __declspec(dllexport) bool QWindow_IsAncestorOf2(const QWindow* self, QWindow* child, AncestorMode mode);
extern __declspec(dllexport) void QWindow_override_virtual_SurfaceType(void* self, intptr_t slot);
SurfaceType QWindow_virtualbase_SurfaceType(const void* self);
extern __declspec(dllexport) void QWindow_override_virtual_Format(void* self, intptr_t slot);
QSurfaceFormat* QWindow_virtualbase_Format(const void* self);
extern __declspec(dllexport) void QWindow_override_virtual_Size(void* self, intptr_t slot);
QSize* QWindow_virtualbase_Size(const void* self);
extern __declspec(dllexport) void QWindow_override_virtual_AccessibleRoot(void* self, intptr_t slot);
QAccessibleInterface* QWindow_virtualbase_AccessibleRoot(const void* self);
extern __declspec(dllexport) void QWindow_override_virtual_FocusObject(void* self, intptr_t slot);
QObject* QWindow_virtualbase_FocusObject(const void* self);
extern __declspec(dllexport) void QWindow_override_virtual_ExposeEvent(void* self, intptr_t slot);
void QWindow_virtualbase_ExposeEvent(void* self, QExposeEvent* param1);
extern __declspec(dllexport) void QWindow_override_virtual_ResizeEvent(void* self, intptr_t slot);
void QWindow_virtualbase_ResizeEvent(void* self, QResizeEvent* param1);
extern __declspec(dllexport) void QWindow_override_virtual_PaintEvent(void* self, intptr_t slot);
void QWindow_virtualbase_PaintEvent(void* self, QPaintEvent* param1);
extern __declspec(dllexport) void QWindow_override_virtual_MoveEvent(void* self, intptr_t slot);
void QWindow_virtualbase_MoveEvent(void* self, QMoveEvent* param1);
extern __declspec(dllexport) void QWindow_override_virtual_FocusInEvent(void* self, intptr_t slot);
void QWindow_virtualbase_FocusInEvent(void* self, QFocusEvent* param1);
extern __declspec(dllexport) void QWindow_override_virtual_FocusOutEvent(void* self, intptr_t slot);
void QWindow_virtualbase_FocusOutEvent(void* self, QFocusEvent* param1);
extern __declspec(dllexport) void QWindow_override_virtual_ShowEvent(void* self, intptr_t slot);
void QWindow_virtualbase_ShowEvent(void* self, QShowEvent* param1);
extern __declspec(dllexport) void QWindow_override_virtual_HideEvent(void* self, intptr_t slot);
void QWindow_virtualbase_HideEvent(void* self, QHideEvent* param1);
extern __declspec(dllexport) void QWindow_override_virtual_CloseEvent(void* self, intptr_t slot);
void QWindow_virtualbase_CloseEvent(void* self, QCloseEvent* param1);
extern __declspec(dllexport) void QWindow_override_virtual_Event(void* self, intptr_t slot);
bool QWindow_virtualbase_Event(void* self, QEvent* param1);
extern __declspec(dllexport) void QWindow_override_virtual_KeyPressEvent(void* self, intptr_t slot);
void QWindow_virtualbase_KeyPressEvent(void* self, QKeyEvent* param1);
extern __declspec(dllexport) void QWindow_override_virtual_KeyReleaseEvent(void* self, intptr_t slot);
void QWindow_virtualbase_KeyReleaseEvent(void* self, QKeyEvent* param1);
extern __declspec(dllexport) void QWindow_override_virtual_MousePressEvent(void* self, intptr_t slot);
void QWindow_virtualbase_MousePressEvent(void* self, QMouseEvent* param1);
extern __declspec(dllexport) void QWindow_override_virtual_MouseReleaseEvent(void* self, intptr_t slot);
void QWindow_virtualbase_MouseReleaseEvent(void* self, QMouseEvent* param1);
extern __declspec(dllexport) void QWindow_override_virtual_MouseDoubleClickEvent(void* self, intptr_t slot);
void QWindow_virtualbase_MouseDoubleClickEvent(void* self, QMouseEvent* param1);
extern __declspec(dllexport) void QWindow_override_virtual_MouseMoveEvent(void* self, intptr_t slot);
void QWindow_virtualbase_MouseMoveEvent(void* self, QMouseEvent* param1);
extern __declspec(dllexport) void QWindow_override_virtual_WheelEvent(void* self, intptr_t slot);
void QWindow_virtualbase_WheelEvent(void* self, QWheelEvent* param1);
extern __declspec(dllexport) void QWindow_override_virtual_TouchEvent(void* self, intptr_t slot);
void QWindow_virtualbase_TouchEvent(void* self, QTouchEvent* param1);
extern __declspec(dllexport) void QWindow_override_virtual_TabletEvent(void* self, intptr_t slot);
void QWindow_virtualbase_TabletEvent(void* self, QTabletEvent* param1);
extern __declspec(dllexport) void QWindow_override_virtual_NativeEvent(void* self, intptr_t slot);
bool QWindow_virtualbase_NativeEvent(void* self, struct miqt_string eventType, void* message, intptr_t* result);
extern __declspec(dllexport) void QWindow_override_virtual_EventFilter(void* self, intptr_t slot);
bool QWindow_virtualbase_EventFilter(void* self, QObject* watched, QEvent* event);
extern __declspec(dllexport) void QWindow_override_virtual_TimerEvent(void* self, intptr_t slot);
void QWindow_virtualbase_TimerEvent(void* self, QTimerEvent* event);
extern __declspec(dllexport) void QWindow_override_virtual_ChildEvent(void* self, intptr_t slot);
void QWindow_virtualbase_ChildEvent(void* self, QChildEvent* event);
extern __declspec(dllexport) void QWindow_override_virtual_CustomEvent(void* self, intptr_t slot);
void QWindow_virtualbase_CustomEvent(void* self, QEvent* event);
extern __declspec(dllexport) void QWindow_override_virtual_ConnectNotify(void* self, intptr_t slot);
void QWindow_virtualbase_ConnectNotify(void* self, QMetaMethod* signal);
extern __declspec(dllexport) void QWindow_override_virtual_DisconnectNotify(void* self, intptr_t slot);
void QWindow_virtualbase_DisconnectNotify(void* self, QMetaMethod* signal);
extern __declspec(dllexport) void QWindow_Delete(QWindow* self, bool isSubclass);

} 
