#pragma once
#ifndef MIQT_QT_GEN_QFILEDIALOG_H
#define MIQT_QT_GEN_QFILEDIALOG_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "../libmiqt/libmiqt.h"
extern "C" {
typedef struct QAbstractFileIconProvider QAbstractFileIconProvider;
typedef struct QAbstractItemDelegate QAbstractItemDelegate;
typedef struct QAbstractProxyModel QAbstractProxyModel;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDialog QDialog;
typedef struct QDir QDir;
typedef struct QEvent QEvent;
typedef struct QFileDialog QFileDialog;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaObject QMetaObject;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QUrl QUrl;
typedef struct QWidget QWidget;

extern __declspec(dllexport) void _GUID_Delete(_GUID* self, bool isSubclass);

extern __declspec(dllexport) void type_info_Delete(type_info* self, bool isSubclass);

extern __declspec(dllexport) QFileDialog* QFileDialog_new(QWidget* parent);
extern __declspec(dllexport) QFileDialog* QFileDialog_new2(QWidget* parent, int f);
extern __declspec(dllexport) QFileDialog* QFileDialog_new3();
extern __declspec(dllexport) QFileDialog* QFileDialog_new4(QWidget* parent, struct miqt_string caption);
extern __declspec(dllexport) QFileDialog* QFileDialog_new5(QWidget* parent, struct miqt_string caption, struct miqt_string directory);
extern __declspec(dllexport) QFileDialog* QFileDialog_new6(QWidget* parent, struct miqt_string caption, struct miqt_string directory, struct miqt_string filter);
extern __declspec(dllexport) void QFileDialog_virtbase(QFileDialog* src, QDialog** outptr_QDialog);
extern __declspec(dllexport) QMetaObject* QFileDialog_MetaObject(const QFileDialog* self);
extern __declspec(dllexport) void* QFileDialog_Metacast(QFileDialog* self, const char* param1);
extern __declspec(dllexport) struct miqt_string QFileDialog_Tr(const char* s);
extern __declspec(dllexport) void QFileDialog_SetDirectory(QFileDialog* self, struct miqt_string directory);
extern __declspec(dllexport) void QFileDialog_SetDirectoryWithDirectory(QFileDialog* self, QDir* directory);
extern __declspec(dllexport) QDir* QFileDialog_Directory(const QFileDialog* self);
extern __declspec(dllexport) void QFileDialog_SetDirectoryUrl(QFileDialog* self, QUrl* directory);
extern __declspec(dllexport) QUrl* QFileDialog_DirectoryUrl(const QFileDialog* self);
extern __declspec(dllexport) void QFileDialog_SelectFile(QFileDialog* self, struct miqt_string filename);
extern __declspec(dllexport) struct miqt_array /* of struct miqt_string */  QFileDialog_SelectedFiles(const QFileDialog* self);
extern __declspec(dllexport) void QFileDialog_SelectUrl(QFileDialog* self, QUrl* url);
extern __declspec(dllexport) struct miqt_array /* of QUrl* */  QFileDialog_SelectedUrls(const QFileDialog* self);
extern __declspec(dllexport) void QFileDialog_SetNameFilter(QFileDialog* self, struct miqt_string filter);
extern __declspec(dllexport) void QFileDialog_SetNameFilters(QFileDialog* self, struct miqt_array /* of struct miqt_string */  filters);
extern __declspec(dllexport) struct miqt_array /* of struct miqt_string */  QFileDialog_NameFilters(const QFileDialog* self);
extern __declspec(dllexport) void QFileDialog_SelectNameFilter(QFileDialog* self, struct miqt_string filter);
extern __declspec(dllexport) struct miqt_string QFileDialog_SelectedMimeTypeFilter(const QFileDialog* self);
extern __declspec(dllexport) struct miqt_string QFileDialog_SelectedNameFilter(const QFileDialog* self);
extern __declspec(dllexport) void QFileDialog_SetMimeTypeFilters(QFileDialog* self, struct miqt_array /* of struct miqt_string */  filters);
extern __declspec(dllexport) struct miqt_array /* of struct miqt_string */  QFileDialog_MimeTypeFilters(const QFileDialog* self);
extern __declspec(dllexport) void QFileDialog_SelectMimeTypeFilter(QFileDialog* self, struct miqt_string filter);
extern __declspec(dllexport) int QFileDialog_Filter(const QFileDialog* self);
extern __declspec(dllexport) void QFileDialog_SetFilter(QFileDialog* self, int filters);
extern __declspec(dllexport) void QFileDialog_SetViewMode(QFileDialog* self, ViewMode mode);
extern __declspec(dllexport) ViewMode QFileDialog_ViewMode(const QFileDialog* self);
extern __declspec(dllexport) void QFileDialog_SetFileMode(QFileDialog* self, FileMode mode);
extern __declspec(dllexport) FileMode QFileDialog_FileMode(const QFileDialog* self);
extern __declspec(dllexport) void QFileDialog_SetAcceptMode(QFileDialog* self, AcceptMode mode);
extern __declspec(dllexport) AcceptMode QFileDialog_AcceptMode(const QFileDialog* self);
extern __declspec(dllexport) void QFileDialog_SetSidebarUrls(QFileDialog* self, struct miqt_array /* of QUrl* */  urls);
extern __declspec(dllexport) struct miqt_array /* of QUrl* */  QFileDialog_SidebarUrls(const QFileDialog* self);
extern __declspec(dllexport) struct miqt_string QFileDialog_SaveState(const QFileDialog* self);
extern __declspec(dllexport) bool QFileDialog_RestoreState(QFileDialog* self, struct miqt_string state);
extern __declspec(dllexport) void QFileDialog_SetDefaultSuffix(QFileDialog* self, struct miqt_string suffix);
extern __declspec(dllexport) struct miqt_string QFileDialog_DefaultSuffix(const QFileDialog* self);
extern __declspec(dllexport) void QFileDialog_SetHistory(QFileDialog* self, struct miqt_array /* of struct miqt_string */  paths);
extern __declspec(dllexport) struct miqt_array /* of struct miqt_string */  QFileDialog_History(const QFileDialog* self);
extern __declspec(dllexport) void QFileDialog_SetItemDelegate(QFileDialog* self, QAbstractItemDelegate* delegate);
extern __declspec(dllexport) QAbstractItemDelegate* QFileDialog_ItemDelegate(const QFileDialog* self);
extern __declspec(dllexport) void QFileDialog_SetIconProvider(QFileDialog* self, QAbstractFileIconProvider* provider);
extern __declspec(dllexport) QAbstractFileIconProvider* QFileDialog_IconProvider(const QFileDialog* self);
extern __declspec(dllexport) void QFileDialog_SetLabelText(QFileDialog* self, DialogLabel label, struct miqt_string text);
extern __declspec(dllexport) struct miqt_string QFileDialog_LabelText(const QFileDialog* self, DialogLabel label);
extern __declspec(dllexport) void QFileDialog_SetSupportedSchemes(QFileDialog* self, struct miqt_array /* of struct miqt_string */  schemes);
extern __declspec(dllexport) struct miqt_array /* of struct miqt_string */  QFileDialog_SupportedSchemes(const QFileDialog* self);
extern __declspec(dllexport) void QFileDialog_SetProxyModel(QFileDialog* self, QAbstractProxyModel* model);
extern __declspec(dllexport) QAbstractProxyModel* QFileDialog_ProxyModel(const QFileDialog* self);
extern __declspec(dllexport) void QFileDialog_SetOption(QFileDialog* self, Option option);
extern __declspec(dllexport) bool QFileDialog_TestOption(const QFileDialog* self, Option option);
extern __declspec(dllexport) void QFileDialog_SetOptions(QFileDialog* self, Options options);
extern __declspec(dllexport) Options QFileDialog_Options(const QFileDialog* self);
extern __declspec(dllexport) void QFileDialog_SetVisible(QFileDialog* self, bool visible);
extern __declspec(dllexport) void QFileDialog_FileSelected(QFileDialog* self, struct miqt_string file);
void QFileDialog_connect_FileSelected(QFileDialog* self, intptr_t slot);
extern __declspec(dllexport) void QFileDialog_FilesSelected(QFileDialog* self, struct miqt_array /* of struct miqt_string */  files);
void QFileDialog_connect_FilesSelected(QFileDialog* self, intptr_t slot);
extern __declspec(dllexport) void QFileDialog_CurrentChanged(QFileDialog* self, struct miqt_string path);
void QFileDialog_connect_CurrentChanged(QFileDialog* self, intptr_t slot);
extern __declspec(dllexport) void QFileDialog_DirectoryEntered(QFileDialog* self, struct miqt_string directory);
void QFileDialog_connect_DirectoryEntered(QFileDialog* self, intptr_t slot);
extern __declspec(dllexport) void QFileDialog_UrlSelected(QFileDialog* self, QUrl* url);
void QFileDialog_connect_UrlSelected(QFileDialog* self, intptr_t slot);
extern __declspec(dllexport) void QFileDialog_UrlsSelected(QFileDialog* self, struct miqt_array /* of QUrl* */  urls);
void QFileDialog_connect_UrlsSelected(QFileDialog* self, intptr_t slot);
extern __declspec(dllexport) void QFileDialog_CurrentUrlChanged(QFileDialog* self, QUrl* url);
void QFileDialog_connect_CurrentUrlChanged(QFileDialog* self, intptr_t slot);
extern __declspec(dllexport) void QFileDialog_DirectoryUrlEntered(QFileDialog* self, QUrl* directory);
void QFileDialog_connect_DirectoryUrlEntered(QFileDialog* self, intptr_t slot);
extern __declspec(dllexport) void QFileDialog_FilterSelected(QFileDialog* self, struct miqt_string filter);
void QFileDialog_connect_FilterSelected(QFileDialog* self, intptr_t slot);
extern __declspec(dllexport) struct miqt_string QFileDialog_GetOpenFileName();
extern __declspec(dllexport) QUrl* QFileDialog_GetOpenFileUrl();
extern __declspec(dllexport) struct miqt_string QFileDialog_GetSaveFileName();
extern __declspec(dllexport) QUrl* QFileDialog_GetSaveFileUrl();
extern __declspec(dllexport) struct miqt_string QFileDialog_GetExistingDirectory();
extern __declspec(dllexport) QUrl* QFileDialog_GetExistingDirectoryUrl();
extern __declspec(dllexport) struct miqt_array /* of struct miqt_string */  QFileDialog_GetOpenFileNames();
extern __declspec(dllexport) struct miqt_array /* of QUrl* */  QFileDialog_GetOpenFileUrls();
extern __declspec(dllexport) void QFileDialog_SaveFileContent(struct miqt_string fileContent, struct miqt_string fileNameHint);
extern __declspec(dllexport) void QFileDialog_Done(QFileDialog* self, int result);
extern __declspec(dllexport) void QFileDialog_Accept(QFileDialog* self);
extern __declspec(dllexport) void QFileDialog_ChangeEvent(QFileDialog* self, QEvent* e);
extern __declspec(dllexport) struct miqt_string QFileDialog_Tr2(const char* s, const char* c);
extern __declspec(dllexport) struct miqt_string QFileDialog_Tr3(const char* s, const char* c, int n);
extern __declspec(dllexport) void QFileDialog_SetOption2(QFileDialog* self, Option option, bool on);
extern __declspec(dllexport) struct miqt_string QFileDialog_GetOpenFileName1(QWidget* parent);
extern __declspec(dllexport) struct miqt_string QFileDialog_GetOpenFileName2(QWidget* parent, struct miqt_string caption);
extern __declspec(dllexport) struct miqt_string QFileDialog_GetOpenFileName3(QWidget* parent, struct miqt_string caption, struct miqt_string dir);
extern __declspec(dllexport) struct miqt_string QFileDialog_GetOpenFileName4(QWidget* parent, struct miqt_string caption, struct miqt_string dir, struct miqt_string filter);
extern __declspec(dllexport) QUrl* QFileDialog_GetOpenFileUrl1(QWidget* parent);
extern __declspec(dllexport) QUrl* QFileDialog_GetOpenFileUrl2(QWidget* parent, struct miqt_string caption);
extern __declspec(dllexport) QUrl* QFileDialog_GetOpenFileUrl3(QWidget* parent, struct miqt_string caption, QUrl* dir);
extern __declspec(dllexport) QUrl* QFileDialog_GetOpenFileUrl4(QWidget* parent, struct miqt_string caption, QUrl* dir, struct miqt_string filter);
extern __declspec(dllexport) struct miqt_string QFileDialog_GetSaveFileName1(QWidget* parent);
extern __declspec(dllexport) struct miqt_string QFileDialog_GetSaveFileName2(QWidget* parent, struct miqt_string caption);
extern __declspec(dllexport) struct miqt_string QFileDialog_GetSaveFileName3(QWidget* parent, struct miqt_string caption, struct miqt_string dir);
extern __declspec(dllexport) struct miqt_string QFileDialog_GetSaveFileName4(QWidget* parent, struct miqt_string caption, struct miqt_string dir, struct miqt_string filter);
extern __declspec(dllexport) QUrl* QFileDialog_GetSaveFileUrl1(QWidget* parent);
extern __declspec(dllexport) QUrl* QFileDialog_GetSaveFileUrl2(QWidget* parent, struct miqt_string caption);
extern __declspec(dllexport) QUrl* QFileDialog_GetSaveFileUrl3(QWidget* parent, struct miqt_string caption, QUrl* dir);
extern __declspec(dllexport) QUrl* QFileDialog_GetSaveFileUrl4(QWidget* parent, struct miqt_string caption, QUrl* dir, struct miqt_string filter);
extern __declspec(dllexport) struct miqt_string QFileDialog_GetExistingDirectory1(QWidget* parent);
extern __declspec(dllexport) struct miqt_string QFileDialog_GetExistingDirectory2(QWidget* parent, struct miqt_string caption);
extern __declspec(dllexport) struct miqt_string QFileDialog_GetExistingDirectory3(QWidget* parent, struct miqt_string caption, struct miqt_string dir);
extern __declspec(dllexport) struct miqt_string QFileDialog_GetExistingDirectory4(QWidget* parent, struct miqt_string caption, struct miqt_string dir, Options options);
extern __declspec(dllexport) QUrl* QFileDialog_GetExistingDirectoryUrl1(QWidget* parent);
extern __declspec(dllexport) QUrl* QFileDialog_GetExistingDirectoryUrl2(QWidget* parent, struct miqt_string caption);
extern __declspec(dllexport) QUrl* QFileDialog_GetExistingDirectoryUrl3(QWidget* parent, struct miqt_string caption, QUrl* dir);
extern __declspec(dllexport) QUrl* QFileDialog_GetExistingDirectoryUrl4(QWidget* parent, struct miqt_string caption, QUrl* dir, Options options);
extern __declspec(dllexport) QUrl* QFileDialog_GetExistingDirectoryUrl5(QWidget* parent, struct miqt_string caption, QUrl* dir, Options options, struct miqt_array /* of struct miqt_string */  supportedSchemes);
extern __declspec(dllexport) struct miqt_array /* of struct miqt_string */  QFileDialog_GetOpenFileNames1(QWidget* parent);
extern __declspec(dllexport) struct miqt_array /* of struct miqt_string */  QFileDialog_GetOpenFileNames2(QWidget* parent, struct miqt_string caption);
extern __declspec(dllexport) struct miqt_array /* of struct miqt_string */  QFileDialog_GetOpenFileNames3(QWidget* parent, struct miqt_string caption, struct miqt_string dir);
extern __declspec(dllexport) struct miqt_array /* of struct miqt_string */  QFileDialog_GetOpenFileNames4(QWidget* parent, struct miqt_string caption, struct miqt_string dir, struct miqt_string filter);
extern __declspec(dllexport) struct miqt_array /* of QUrl* */  QFileDialog_GetOpenFileUrls1(QWidget* parent);
extern __declspec(dllexport) struct miqt_array /* of QUrl* */  QFileDialog_GetOpenFileUrls2(QWidget* parent, struct miqt_string caption);
extern __declspec(dllexport) struct miqt_array /* of QUrl* */  QFileDialog_GetOpenFileUrls3(QWidget* parent, struct miqt_string caption, QUrl* dir);
extern __declspec(dllexport) struct miqt_array /* of QUrl* */  QFileDialog_GetOpenFileUrls4(QWidget* parent, struct miqt_string caption, QUrl* dir, struct miqt_string filter);
extern __declspec(dllexport) void QFileDialog_SaveFileContent3(struct miqt_string fileContent, struct miqt_string fileNameHint, QWidget* parent);
extern __declspec(dllexport) void QFileDialog_override_virtual_SetVisible(void* self, intptr_t slot);
void QFileDialog_virtualbase_SetVisible(void* self, bool visible);
extern __declspec(dllexport) void QFileDialog_override_virtual_Done(void* self, intptr_t slot);
void QFileDialog_virtualbase_Done(void* self, int result);
extern __declspec(dllexport) void QFileDialog_override_virtual_Accept(void* self, intptr_t slot);
void QFileDialog_virtualbase_Accept(void* self);
extern __declspec(dllexport) void QFileDialog_override_virtual_ChangeEvent(void* self, intptr_t slot);
void QFileDialog_virtualbase_ChangeEvent(void* self, QEvent* e);
extern __declspec(dllexport) void QFileDialog_override_virtual_SizeHint(void* self, intptr_t slot);
QSize* QFileDialog_virtualbase_SizeHint(const void* self);
extern __declspec(dllexport) void QFileDialog_override_virtual_MinimumSizeHint(void* self, intptr_t slot);
QSize* QFileDialog_virtualbase_MinimumSizeHint(const void* self);
extern __declspec(dllexport) void QFileDialog_override_virtual_Open(void* self, intptr_t slot);
void QFileDialog_virtualbase_Open(void* self);
extern __declspec(dllexport) void QFileDialog_override_virtual_Exec(void* self, intptr_t slot);
int QFileDialog_virtualbase_Exec(void* self);
extern __declspec(dllexport) void QFileDialog_override_virtual_Reject(void* self, intptr_t slot);
void QFileDialog_virtualbase_Reject(void* self);
extern __declspec(dllexport) void QFileDialog_override_virtual_KeyPressEvent(void* self, intptr_t slot);
void QFileDialog_virtualbase_KeyPressEvent(void* self, QKeyEvent* param1);
extern __declspec(dllexport) void QFileDialog_override_virtual_CloseEvent(void* self, intptr_t slot);
void QFileDialog_virtualbase_CloseEvent(void* self, QCloseEvent* param1);
extern __declspec(dllexport) void QFileDialog_override_virtual_ShowEvent(void* self, intptr_t slot);
void QFileDialog_virtualbase_ShowEvent(void* self, QShowEvent* param1);
extern __declspec(dllexport) void QFileDialog_override_virtual_ResizeEvent(void* self, intptr_t slot);
void QFileDialog_virtualbase_ResizeEvent(void* self, QResizeEvent* param1);
extern __declspec(dllexport) void QFileDialog_override_virtual_ContextMenuEvent(void* self, intptr_t slot);
void QFileDialog_virtualbase_ContextMenuEvent(void* self, QContextMenuEvent* param1);
extern __declspec(dllexport) void QFileDialog_override_virtual_EventFilter(void* self, intptr_t slot);
bool QFileDialog_virtualbase_EventFilter(void* self, QObject* param1, QEvent* param2);
extern __declspec(dllexport) void QFileDialog_Delete(QFileDialog* self, bool isSubclass);

} 
