#pragma once
#ifndef MIQT_QT_GEN_QRECT_H
#define MIQT_QT_GEN_QRECT_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "../libmiqt/libmiqt.h"
extern "C" {
typedef struct QMargins QMargins;
typedef struct QMarginsF QMarginsF;
typedef struct QPoint QPoint;
typedef struct QPointF QPointF;
typedef struct QRect QRect;
typedef struct QRectF QRectF;
typedef struct QSize QSize;
typedef struct QSizeF QSizeF;
typedef struct _GUID _GUID;
typedef struct type_info type_info;

extern __declspec(dllexport) void _GUID_Delete(_GUID* self, bool isSubclass);

extern __declspec(dllexport) void type_info_Delete(type_info* self, bool isSubclass);

extern __declspec(dllexport) QRect* QRect_new();
extern __declspec(dllexport) QRect* QRect_new2(QPoint* topleft, QPoint* bottomright);
extern __declspec(dllexport) QRect* QRect_new3(QPoint* topleft, QSize* size);
extern __declspec(dllexport) QRect* QRect_new4(int left, int top, int width, int height);
extern __declspec(dllexport) QRect* QRect_new5(QRect* param1);
extern __declspec(dllexport) bool QRect_IsNull(const QRect* self);
extern __declspec(dllexport) bool QRect_IsEmpty(const QRect* self);
extern __declspec(dllexport) bool QRect_IsValid(const QRect* self);
extern __declspec(dllexport) int QRect_Left(const QRect* self);
extern __declspec(dllexport) int QRect_Top(const QRect* self);
extern __declspec(dllexport) int QRect_Right(const QRect* self);
extern __declspec(dllexport) int QRect_Bottom(const QRect* self);
extern __declspec(dllexport) QRect* QRect_Normalized(const QRect* self);
extern __declspec(dllexport) int QRect_X(const QRect* self);
extern __declspec(dllexport) int QRect_Y(const QRect* self);
extern __declspec(dllexport) void QRect_SetLeft(QRect* self, int pos);
extern __declspec(dllexport) void QRect_SetTop(QRect* self, int pos);
extern __declspec(dllexport) void QRect_SetRight(QRect* self, int pos);
extern __declspec(dllexport) void QRect_SetBottom(QRect* self, int pos);
extern __declspec(dllexport) void QRect_SetX(QRect* self, int x);
extern __declspec(dllexport) void QRect_SetY(QRect* self, int y);
extern __declspec(dllexport) void QRect_SetTopLeft(QRect* self, QPoint* p);
extern __declspec(dllexport) void QRect_SetBottomRight(QRect* self, QPoint* p);
extern __declspec(dllexport) void QRect_SetTopRight(QRect* self, QPoint* p);
extern __declspec(dllexport) void QRect_SetBottomLeft(QRect* self, QPoint* p);
extern __declspec(dllexport) QPoint* QRect_TopLeft(const QRect* self);
extern __declspec(dllexport) QPoint* QRect_BottomRight(const QRect* self);
extern __declspec(dllexport) QPoint* QRect_TopRight(const QRect* self);
extern __declspec(dllexport) QPoint* QRect_BottomLeft(const QRect* self);
extern __declspec(dllexport) QPoint* QRect_Center(const QRect* self);
extern __declspec(dllexport) void QRect_MoveLeft(QRect* self, int pos);
extern __declspec(dllexport) void QRect_MoveTop(QRect* self, int pos);
extern __declspec(dllexport) void QRect_MoveRight(QRect* self, int pos);
extern __declspec(dllexport) void QRect_MoveBottom(QRect* self, int pos);
extern __declspec(dllexport) void QRect_MoveTopLeft(QRect* self, QPoint* p);
extern __declspec(dllexport) void QRect_MoveBottomRight(QRect* self, QPoint* p);
extern __declspec(dllexport) void QRect_MoveTopRight(QRect* self, QPoint* p);
extern __declspec(dllexport) void QRect_MoveBottomLeft(QRect* self, QPoint* p);
extern __declspec(dllexport) void QRect_MoveCenter(QRect* self, QPoint* p);
extern __declspec(dllexport) void QRect_Translate(QRect* self, int dx, int dy);
extern __declspec(dllexport) void QRect_TranslateWithQPoint(QRect* self, QPoint* p);
extern __declspec(dllexport) QRect* QRect_Translated(const QRect* self, int dx, int dy);
extern __declspec(dllexport) QRect* QRect_TranslatedWithQPoint(const QRect* self, QPoint* p);
extern __declspec(dllexport) QRect* QRect_Transposed(const QRect* self);
extern __declspec(dllexport) void QRect_MoveTo(QRect* self, int x, int t);
extern __declspec(dllexport) void QRect_MoveToWithQPoint(QRect* self, QPoint* p);
extern __declspec(dllexport) void QRect_SetRect(QRect* self, int x, int y, int w, int h);
extern __declspec(dllexport) void QRect_GetRect(const QRect* self, int* x, int* y, int* w, int* h);
extern __declspec(dllexport) void QRect_SetCoords(QRect* self, int x1, int y1, int x2, int y2);
extern __declspec(dllexport) void QRect_GetCoords(const QRect* self, int* x1, int* y1, int* x2, int* y2);
extern __declspec(dllexport) void QRect_Adjust(QRect* self, int x1, int y1, int x2, int y2);
extern __declspec(dllexport) QRect* QRect_Adjusted(const QRect* self, int x1, int y1, int x2, int y2);
extern __declspec(dllexport) QSize* QRect_Size(const QRect* self);
extern __declspec(dllexport) int QRect_Width(const QRect* self);
extern __declspec(dllexport) int QRect_Height(const QRect* self);
extern __declspec(dllexport) void QRect_SetWidth(QRect* self, int w);
extern __declspec(dllexport) void QRect_SetHeight(QRect* self, int h);
extern __declspec(dllexport) void QRect_SetSize(QRect* self, QSize* s);
extern __declspec(dllexport) QRect* QRect_OperatorBitwiseOr(const QRect* self, QRect* r);
extern __declspec(dllexport) QRect* QRect_OperatorBitwiseAnd(const QRect* self, QRect* r);
extern __declspec(dllexport) void QRect_OperatorBitwiseOrAssign(QRect* self, QRect* r);
extern __declspec(dllexport) void QRect_OperatorBitwiseAndAssign(QRect* self, QRect* r);
extern __declspec(dllexport) bool QRect_Contains(const QRect* self, QRect* r);
extern __declspec(dllexport) bool QRect_ContainsWithQPoint(const QRect* self, QPoint* p);
extern __declspec(dllexport) bool QRect_Contains2(const QRect* self, int x, int y);
extern __declspec(dllexport) bool QRect_Contains3(const QRect* self, int x, int y, bool proper);
extern __declspec(dllexport) QRect* QRect_United(const QRect* self, QRect* other);
extern __declspec(dllexport) QRect* QRect_Intersected(const QRect* self, QRect* other);
extern __declspec(dllexport) bool QRect_Intersects(const QRect* self, QRect* r);
extern __declspec(dllexport) QRect* QRect_MarginsAdded(const QRect* self, QMargins* margins);
extern __declspec(dllexport) QRect* QRect_MarginsRemoved(const QRect* self, QMargins* margins);
extern __declspec(dllexport) QRect* QRect_OperatorPlusAssign(QRect* self, QMargins* margins);
extern __declspec(dllexport) QRect* QRect_OperatorMinusAssign(QRect* self, QMargins* margins);
extern __declspec(dllexport) QRect* QRect_Span(QPoint* p1, QPoint* p2);
extern __declspec(dllexport) QRectF* QRect_ToRectF(const QRect* self);
extern __declspec(dllexport) bool QRect_Contains22(const QRect* self, QRect* r, bool proper);
extern __declspec(dllexport) bool QRect_Contains23(const QRect* self, QPoint* p, bool proper);
extern __declspec(dllexport) void QRect_Delete(QRect* self, bool isSubclass);

extern __declspec(dllexport) QRectF* QRectF_new();
extern __declspec(dllexport) QRectF* QRectF_new2(QPointF* topleft, QSizeF* size);
extern __declspec(dllexport) QRectF* QRectF_new3(QPointF* topleft, QPointF* bottomRight);
extern __declspec(dllexport) QRectF* QRectF_new4(double left, double top, double width, double height);
extern __declspec(dllexport) QRectF* QRectF_new5(QRect* rect);
extern __declspec(dllexport) QRectF* QRectF_new6(QRectF* param1);
extern __declspec(dllexport) bool QRectF_IsNull(const QRectF* self);
extern __declspec(dllexport) bool QRectF_IsEmpty(const QRectF* self);
extern __declspec(dllexport) bool QRectF_IsValid(const QRectF* self);
extern __declspec(dllexport) QRectF* QRectF_Normalized(const QRectF* self);
extern __declspec(dllexport) double QRectF_Left(const QRectF* self);
extern __declspec(dllexport) double QRectF_Top(const QRectF* self);
extern __declspec(dllexport) double QRectF_Right(const QRectF* self);
extern __declspec(dllexport) double QRectF_Bottom(const QRectF* self);
extern __declspec(dllexport) double QRectF_X(const QRectF* self);
extern __declspec(dllexport) double QRectF_Y(const QRectF* self);
extern __declspec(dllexport) void QRectF_SetLeft(QRectF* self, double pos);
extern __declspec(dllexport) void QRectF_SetTop(QRectF* self, double pos);
extern __declspec(dllexport) void QRectF_SetRight(QRectF* self, double pos);
extern __declspec(dllexport) void QRectF_SetBottom(QRectF* self, double pos);
extern __declspec(dllexport) void QRectF_SetX(QRectF* self, double pos);
extern __declspec(dllexport) void QRectF_SetY(QRectF* self, double pos);
extern __declspec(dllexport) QPointF* QRectF_TopLeft(const QRectF* self);
extern __declspec(dllexport) QPointF* QRectF_BottomRight(const QRectF* self);
extern __declspec(dllexport) QPointF* QRectF_TopRight(const QRectF* self);
extern __declspec(dllexport) QPointF* QRectF_BottomLeft(const QRectF* self);
extern __declspec(dllexport) QPointF* QRectF_Center(const QRectF* self);
extern __declspec(dllexport) void QRectF_SetTopLeft(QRectF* self, QPointF* p);
extern __declspec(dllexport) void QRectF_SetBottomRight(QRectF* self, QPointF* p);
extern __declspec(dllexport) void QRectF_SetTopRight(QRectF* self, QPointF* p);
extern __declspec(dllexport) void QRectF_SetBottomLeft(QRectF* self, QPointF* p);
extern __declspec(dllexport) void QRectF_MoveLeft(QRectF* self, double pos);
extern __declspec(dllexport) void QRectF_MoveTop(QRectF* self, double pos);
extern __declspec(dllexport) void QRectF_MoveRight(QRectF* self, double pos);
extern __declspec(dllexport) void QRectF_MoveBottom(QRectF* self, double pos);
extern __declspec(dllexport) void QRectF_MoveTopLeft(QRectF* self, QPointF* p);
extern __declspec(dllexport) void QRectF_MoveBottomRight(QRectF* self, QPointF* p);
extern __declspec(dllexport) void QRectF_MoveTopRight(QRectF* self, QPointF* p);
extern __declspec(dllexport) void QRectF_MoveBottomLeft(QRectF* self, QPointF* p);
extern __declspec(dllexport) void QRectF_MoveCenter(QRectF* self, QPointF* p);
extern __declspec(dllexport) void QRectF_Translate(QRectF* self, double dx, double dy);
extern __declspec(dllexport) void QRectF_TranslateWithQPointF(QRectF* self, QPointF* p);
extern __declspec(dllexport) QRectF* QRectF_Translated(const QRectF* self, double dx, double dy);
extern __declspec(dllexport) QRectF* QRectF_TranslatedWithQPointF(const QRectF* self, QPointF* p);
extern __declspec(dllexport) QRectF* QRectF_Transposed(const QRectF* self);
extern __declspec(dllexport) void QRectF_MoveTo(QRectF* self, double x, double y);
extern __declspec(dllexport) void QRectF_MoveToWithQPointF(QRectF* self, QPointF* p);
extern __declspec(dllexport) void QRectF_SetRect(QRectF* self, double x, double y, double w, double h);
extern __declspec(dllexport) void QRectF_GetRect(const QRectF* self, double* x, double* y, double* w, double* h);
extern __declspec(dllexport) void QRectF_SetCoords(QRectF* self, double x1, double y1, double x2, double y2);
extern __declspec(dllexport) void QRectF_GetCoords(const QRectF* self, double* x1, double* y1, double* x2, double* y2);
extern __declspec(dllexport) void QRectF_Adjust(QRectF* self, double x1, double y1, double x2, double y2);
extern __declspec(dllexport) QRectF* QRectF_Adjusted(const QRectF* self, double x1, double y1, double x2, double y2);
extern __declspec(dllexport) QSizeF* QRectF_Size(const QRectF* self);
extern __declspec(dllexport) double QRectF_Width(const QRectF* self);
extern __declspec(dllexport) double QRectF_Height(const QRectF* self);
extern __declspec(dllexport) void QRectF_SetWidth(QRectF* self, double w);
extern __declspec(dllexport) void QRectF_SetHeight(QRectF* self, double h);
extern __declspec(dllexport) void QRectF_SetSize(QRectF* self, QSizeF* s);
extern __declspec(dllexport) QRectF* QRectF_OperatorBitwiseOr(const QRectF* self, QRectF* r);
extern __declspec(dllexport) QRectF* QRectF_OperatorBitwiseAnd(const QRectF* self, QRectF* r);
extern __declspec(dllexport) void QRectF_OperatorBitwiseOrAssign(QRectF* self, QRectF* r);
extern __declspec(dllexport) void QRectF_OperatorBitwiseAndAssign(QRectF* self, QRectF* r);
extern __declspec(dllexport) bool QRectF_Contains(const QRectF* self, QRectF* r);
extern __declspec(dllexport) bool QRectF_ContainsWithQPointF(const QRectF* self, QPointF* p);
extern __declspec(dllexport) bool QRectF_Contains2(const QRectF* self, double x, double y);
extern __declspec(dllexport) QRectF* QRectF_United(const QRectF* self, QRectF* other);
extern __declspec(dllexport) QRectF* QRectF_Intersected(const QRectF* self, QRectF* other);
extern __declspec(dllexport) bool QRectF_Intersects(const QRectF* self, QRectF* r);
extern __declspec(dllexport) QRectF* QRectF_MarginsAdded(const QRectF* self, QMarginsF* margins);
extern __declspec(dllexport) QRectF* QRectF_MarginsRemoved(const QRectF* self, QMarginsF* margins);
extern __declspec(dllexport) QRectF* QRectF_OperatorPlusAssign(QRectF* self, QMarginsF* margins);
extern __declspec(dllexport) QRectF* QRectF_OperatorMinusAssign(QRectF* self, QMarginsF* margins);
extern __declspec(dllexport) QRect* QRectF_ToRect(const QRectF* self);
extern __declspec(dllexport) QRect* QRectF_ToAlignedRect(const QRectF* self);
extern __declspec(dllexport) void QRectF_Delete(QRectF* self, bool isSubclass);

} 
