#pragma once
#ifndef MIQT_QT_GEN_QLISTVIEW_H
#define MIQT_QT_GEN_QLISTVIEW_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "../libmiqt/libmiqt.h"
extern "C" {
typedef struct QAbstractItemDelegate QAbstractItemDelegate;
typedef struct QAbstractItemModel QAbstractItemModel;
typedef struct QAbstractItemView QAbstractItemView;
typedef struct QAbstractScrollArea QAbstractScrollArea;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFrame QFrame;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QItemSelection QItemSelection;
typedef struct QItemSelectionModel QItemSelectionModel;
typedef struct QKeyEvent QKeyEvent;
typedef struct QListView QListView;
typedef struct QMetaObject QMetaObject;
typedef struct QModelIndex QModelIndex;
typedef struct QMouseEvent QMouseEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPoint QPoint;
typedef struct QRect QRect;
typedef struct QRegion QRegion;
typedef struct QResizeEvent QResizeEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionViewItem QStyleOptionViewItem;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;

extern __declspec(dllexport) void _GUID_Delete(_GUID* self, bool isSubclass);

extern __declspec(dllexport) void type_info_Delete(type_info* self, bool isSubclass);

extern __declspec(dllexport) QListView* QListView_new(QWidget* parent);
extern __declspec(dllexport) QListView* QListView_new2();
extern __declspec(dllexport) void QListView_virtbase(QListView* src, QAbstractItemView** outptr_QAbstractItemView);
extern __declspec(dllexport) QMetaObject* QListView_MetaObject(const QListView* self);
extern __declspec(dllexport) void* QListView_Metacast(QListView* self, const char* param1);
extern __declspec(dllexport) struct miqt_string QListView_Tr(const char* s);
extern __declspec(dllexport) void QListView_SetMovement(QListView* self, Movement movement);
extern __declspec(dllexport) Movement QListView_Movement(const QListView* self);
extern __declspec(dllexport) void QListView_SetFlow(QListView* self, Flow flow);
extern __declspec(dllexport) Flow QListView_Flow(const QListView* self);
extern __declspec(dllexport) void QListView_SetWrapping(QListView* self, bool enable);
extern __declspec(dllexport) bool QListView_IsWrapping(const QListView* self);
extern __declspec(dllexport) void QListView_SetResizeMode(QListView* self, ResizeMode mode);
extern __declspec(dllexport) ResizeMode QListView_ResizeMode(const QListView* self);
extern __declspec(dllexport) void QListView_SetLayoutMode(QListView* self, LayoutMode mode);
extern __declspec(dllexport) LayoutMode QListView_LayoutMode(const QListView* self);
extern __declspec(dllexport) void QListView_SetSpacing(QListView* self, int space);
extern __declspec(dllexport) int QListView_Spacing(const QListView* self);
extern __declspec(dllexport) void QListView_SetBatchSize(QListView* self, int batchSize);
extern __declspec(dllexport) int QListView_BatchSize(const QListView* self);
extern __declspec(dllexport) void QListView_SetGridSize(QListView* self, QSize* size);
extern __declspec(dllexport) QSize* QListView_GridSize(const QListView* self);
extern __declspec(dllexport) void QListView_SetViewMode(QListView* self, ViewMode mode);
extern __declspec(dllexport) ViewMode QListView_ViewMode(const QListView* self);
extern __declspec(dllexport) void QListView_ClearPropertyFlags(QListView* self);
extern __declspec(dllexport) bool QListView_IsRowHidden(const QListView* self, int row);
extern __declspec(dllexport) void QListView_SetRowHidden(QListView* self, int row, bool hide);
extern __declspec(dllexport) void QListView_SetModelColumn(QListView* self, int column);
extern __declspec(dllexport) int QListView_ModelColumn(const QListView* self);
extern __declspec(dllexport) void QListView_SetUniformItemSizes(QListView* self, bool enable);
extern __declspec(dllexport) bool QListView_UniformItemSizes(const QListView* self);
extern __declspec(dllexport) void QListView_SetWordWrap(QListView* self, bool on);
extern __declspec(dllexport) bool QListView_WordWrap(const QListView* self);
extern __declspec(dllexport) void QListView_SetSelectionRectVisible(QListView* self, bool show);
extern __declspec(dllexport) bool QListView_IsSelectionRectVisible(const QListView* self);
extern __declspec(dllexport) void QListView_SetItemAlignment(QListView* self, int alignment);
extern __declspec(dllexport) int QListView_ItemAlignment(const QListView* self);
extern __declspec(dllexport) QRect* QListView_VisualRect(const QListView* self, QModelIndex* index);
extern __declspec(dllexport) void QListView_ScrollTo(QListView* self, QModelIndex* index, ScrollHint hint);
extern __declspec(dllexport) QModelIndex* QListView_IndexAt(const QListView* self, QPoint* p);
extern __declspec(dllexport) void QListView_DoItemsLayout(QListView* self);
extern __declspec(dllexport) void QListView_Reset(QListView* self);
extern __declspec(dllexport) void QListView_SetRootIndex(QListView* self, QModelIndex* index);
extern __declspec(dllexport) void QListView_IndexesMoved(QListView* self, struct miqt_array /* of QModelIndex* */  indexes);
void QListView_connect_IndexesMoved(QListView* self, intptr_t slot);
extern __declspec(dllexport) bool QListView_Event(QListView* self, QEvent* e);
extern __declspec(dllexport) void QListView_ScrollContentsBy(QListView* self, int dx, int dy);
extern __declspec(dllexport) void QListView_DataChanged(QListView* self, QModelIndex* topLeft, QModelIndex* bottomRight, struct miqt_array /* of int */  roles);
extern __declspec(dllexport) void QListView_RowsInserted(QListView* self, QModelIndex* parent, int start, int end);
extern __declspec(dllexport) void QListView_RowsAboutToBeRemoved(QListView* self, QModelIndex* parent, int start, int end);
extern __declspec(dllexport) void QListView_MouseMoveEvent(QListView* self, QMouseEvent* e);
extern __declspec(dllexport) void QListView_MouseReleaseEvent(QListView* self, QMouseEvent* e);
extern __declspec(dllexport) void QListView_WheelEvent(QListView* self, QWheelEvent* e);
extern __declspec(dllexport) void QListView_TimerEvent(QListView* self, QTimerEvent* e);
extern __declspec(dllexport) void QListView_ResizeEvent(QListView* self, QResizeEvent* e);
extern __declspec(dllexport) void QListView_DragMoveEvent(QListView* self, QDragMoveEvent* e);
extern __declspec(dllexport) void QListView_DragLeaveEvent(QListView* self, QDragLeaveEvent* e);
extern __declspec(dllexport) void QListView_DropEvent(QListView* self, QDropEvent* e);
extern __declspec(dllexport) void QListView_StartDrag(QListView* self, int supportedActions);
extern __declspec(dllexport) void QListView_InitViewItemOption(const QListView* self, QStyleOptionViewItem* option);
extern __declspec(dllexport) void QListView_PaintEvent(QListView* self, QPaintEvent* e);
extern __declspec(dllexport) int QListView_HorizontalOffset(const QListView* self);
extern __declspec(dllexport) int QListView_VerticalOffset(const QListView* self);
extern __declspec(dllexport) QModelIndex* QListView_MoveCursor(QListView* self, CursorAction cursorAction, int modifiers);
extern __declspec(dllexport) void QListView_SetSelection(QListView* self, QRect* rect, int command);
extern __declspec(dllexport) QRegion* QListView_VisualRegionForSelection(const QListView* self, QItemSelection* selection);
extern __declspec(dllexport) struct miqt_array /* of QModelIndex* */  QListView_SelectedIndexes(const QListView* self);
extern __declspec(dllexport) void QListView_UpdateGeometries(QListView* self);
extern __declspec(dllexport) bool QListView_IsIndexHidden(const QListView* self, QModelIndex* index);
extern __declspec(dllexport) void QListView_SelectionChanged(QListView* self, QItemSelection* selected, QItemSelection* deselected);
extern __declspec(dllexport) void QListView_CurrentChanged(QListView* self, QModelIndex* current, QModelIndex* previous);
extern __declspec(dllexport) QSize* QListView_ViewportSizeHint(const QListView* self);
extern __declspec(dllexport) struct miqt_string QListView_Tr2(const char* s, const char* c);
extern __declspec(dllexport) struct miqt_string QListView_Tr3(const char* s, const char* c, int n);
extern __declspec(dllexport) void QListView_override_virtual_VisualRect(void* self, intptr_t slot);
QRect* QListView_virtualbase_VisualRect(const void* self, QModelIndex* index);
extern __declspec(dllexport) void QListView_override_virtual_ScrollTo(void* self, intptr_t slot);
void QListView_virtualbase_ScrollTo(void* self, QModelIndex* index, ScrollHint hint);
extern __declspec(dllexport) void QListView_override_virtual_IndexAt(void* self, intptr_t slot);
QModelIndex* QListView_virtualbase_IndexAt(const void* self, QPoint* p);
extern __declspec(dllexport) void QListView_override_virtual_DoItemsLayout(void* self, intptr_t slot);
void QListView_virtualbase_DoItemsLayout(void* self);
extern __declspec(dllexport) void QListView_override_virtual_Reset(void* self, intptr_t slot);
void QListView_virtualbase_Reset(void* self);
extern __declspec(dllexport) void QListView_override_virtual_SetRootIndex(void* self, intptr_t slot);
void QListView_virtualbase_SetRootIndex(void* self, QModelIndex* index);
extern __declspec(dllexport) void QListView_override_virtual_Event(void* self, intptr_t slot);
bool QListView_virtualbase_Event(void* self, QEvent* e);
extern __declspec(dllexport) void QListView_override_virtual_ScrollContentsBy(void* self, intptr_t slot);
void QListView_virtualbase_ScrollContentsBy(void* self, int dx, int dy);
extern __declspec(dllexport) void QListView_override_virtual_DataChanged(void* self, intptr_t slot);
void QListView_virtualbase_DataChanged(void* self, QModelIndex* topLeft, QModelIndex* bottomRight, struct miqt_array /* of int */  roles);
extern __declspec(dllexport) void QListView_override_virtual_RowsInserted(void* self, intptr_t slot);
void QListView_virtualbase_RowsInserted(void* self, QModelIndex* parent, int start, int end);
extern __declspec(dllexport) void QListView_override_virtual_RowsAboutToBeRemoved(void* self, intptr_t slot);
void QListView_virtualbase_RowsAboutToBeRemoved(void* self, QModelIndex* parent, int start, int end);
extern __declspec(dllexport) void QListView_override_virtual_MouseMoveEvent(void* self, intptr_t slot);
void QListView_virtualbase_MouseMoveEvent(void* self, QMouseEvent* e);
extern __declspec(dllexport) void QListView_override_virtual_MouseReleaseEvent(void* self, intptr_t slot);
void QListView_virtualbase_MouseReleaseEvent(void* self, QMouseEvent* e);
extern __declspec(dllexport) void QListView_override_virtual_WheelEvent(void* self, intptr_t slot);
void QListView_virtualbase_WheelEvent(void* self, QWheelEvent* e);
extern __declspec(dllexport) void QListView_override_virtual_TimerEvent(void* self, intptr_t slot);
void QListView_virtualbase_TimerEvent(void* self, QTimerEvent* e);
extern __declspec(dllexport) void QListView_override_virtual_ResizeEvent(void* self, intptr_t slot);
void QListView_virtualbase_ResizeEvent(void* self, QResizeEvent* e);
extern __declspec(dllexport) void QListView_override_virtual_DragMoveEvent(void* self, intptr_t slot);
void QListView_virtualbase_DragMoveEvent(void* self, QDragMoveEvent* e);
extern __declspec(dllexport) void QListView_override_virtual_DragLeaveEvent(void* self, intptr_t slot);
void QListView_virtualbase_DragLeaveEvent(void* self, QDragLeaveEvent* e);
extern __declspec(dllexport) void QListView_override_virtual_DropEvent(void* self, intptr_t slot);
void QListView_virtualbase_DropEvent(void* self, QDropEvent* e);
extern __declspec(dllexport) void QListView_override_virtual_StartDrag(void* self, intptr_t slot);
void QListView_virtualbase_StartDrag(void* self, int supportedActions);
extern __declspec(dllexport) void QListView_override_virtual_InitViewItemOption(void* self, intptr_t slot);
void QListView_virtualbase_InitViewItemOption(const void* self, QStyleOptionViewItem* option);
extern __declspec(dllexport) void QListView_override_virtual_PaintEvent(void* self, intptr_t slot);
void QListView_virtualbase_PaintEvent(void* self, QPaintEvent* e);
extern __declspec(dllexport) void QListView_override_virtual_HorizontalOffset(void* self, intptr_t slot);
int QListView_virtualbase_HorizontalOffset(const void* self);
extern __declspec(dllexport) void QListView_override_virtual_VerticalOffset(void* self, intptr_t slot);
int QListView_virtualbase_VerticalOffset(const void* self);
extern __declspec(dllexport) void QListView_override_virtual_MoveCursor(void* self, intptr_t slot);
QModelIndex* QListView_virtualbase_MoveCursor(void* self, CursorAction cursorAction, int modifiers);
extern __declspec(dllexport) void QListView_override_virtual_SetSelection(void* self, intptr_t slot);
void QListView_virtualbase_SetSelection(void* self, QRect* rect, int command);
extern __declspec(dllexport) void QListView_override_virtual_VisualRegionForSelection(void* self, intptr_t slot);
QRegion* QListView_virtualbase_VisualRegionForSelection(const void* self, QItemSelection* selection);
extern __declspec(dllexport) void QListView_override_virtual_SelectedIndexes(void* self, intptr_t slot);
struct miqt_array /* of QModelIndex* */  QListView_virtualbase_SelectedIndexes(const void* self);
extern __declspec(dllexport) void QListView_override_virtual_UpdateGeometries(void* self, intptr_t slot);
void QListView_virtualbase_UpdateGeometries(void* self);
extern __declspec(dllexport) void QListView_override_virtual_IsIndexHidden(void* self, intptr_t slot);
bool QListView_virtualbase_IsIndexHidden(const void* self, QModelIndex* index);
extern __declspec(dllexport) void QListView_override_virtual_SelectionChanged(void* self, intptr_t slot);
void QListView_virtualbase_SelectionChanged(void* self, QItemSelection* selected, QItemSelection* deselected);
extern __declspec(dllexport) void QListView_override_virtual_CurrentChanged(void* self, intptr_t slot);
void QListView_virtualbase_CurrentChanged(void* self, QModelIndex* current, QModelIndex* previous);
extern __declspec(dllexport) void QListView_override_virtual_ViewportSizeHint(void* self, intptr_t slot);
QSize* QListView_virtualbase_ViewportSizeHint(const void* self);
extern __declspec(dllexport) void QListView_override_virtual_SetModel(void* self, intptr_t slot);
void QListView_virtualbase_SetModel(void* self, QAbstractItemModel* model);
extern __declspec(dllexport) void QListView_override_virtual_SetSelectionModel(void* self, intptr_t slot);
void QListView_virtualbase_SetSelectionModel(void* self, QItemSelectionModel* selectionModel);
extern __declspec(dllexport) void QListView_override_virtual_KeyboardSearch(void* self, intptr_t slot);
void QListView_virtualbase_KeyboardSearch(void* self, struct miqt_string search);
extern __declspec(dllexport) void QListView_override_virtual_SizeHintForRow(void* self, intptr_t slot);
int QListView_virtualbase_SizeHintForRow(const void* self, int row);
extern __declspec(dllexport) void QListView_override_virtual_SizeHintForColumn(void* self, intptr_t slot);
int QListView_virtualbase_SizeHintForColumn(const void* self, int column);
extern __declspec(dllexport) void QListView_override_virtual_ItemDelegateForIndex(void* self, intptr_t slot);
QAbstractItemDelegate* QListView_virtualbase_ItemDelegateForIndex(const void* self, QModelIndex* index);
extern __declspec(dllexport) void QListView_override_virtual_InputMethodQuery(void* self, intptr_t slot);
QVariant* QListView_virtualbase_InputMethodQuery(const void* self, int query);
extern __declspec(dllexport) void QListView_override_virtual_SelectAll(void* self, intptr_t slot);
void QListView_virtualbase_SelectAll(void* self);
extern __declspec(dllexport) void QListView_override_virtual_UpdateEditorData(void* self, intptr_t slot);
void QListView_virtualbase_UpdateEditorData(void* self);
extern __declspec(dllexport) void QListView_override_virtual_UpdateEditorGeometries(void* self, intptr_t slot);
void QListView_virtualbase_UpdateEditorGeometries(void* self);
extern __declspec(dllexport) void QListView_override_virtual_VerticalScrollbarAction(void* self, intptr_t slot);
void QListView_virtualbase_VerticalScrollbarAction(void* self, int action);
extern __declspec(dllexport) void QListView_override_virtual_HorizontalScrollbarAction(void* self, intptr_t slot);
void QListView_virtualbase_HorizontalScrollbarAction(void* self, int action);
extern __declspec(dllexport) void QListView_override_virtual_VerticalScrollbarValueChanged(void* self, intptr_t slot);
void QListView_virtualbase_VerticalScrollbarValueChanged(void* self, int value);
extern __declspec(dllexport) void QListView_override_virtual_HorizontalScrollbarValueChanged(void* self, intptr_t slot);
void QListView_virtualbase_HorizontalScrollbarValueChanged(void* self, int value);
extern __declspec(dllexport) void QListView_override_virtual_CloseEditor(void* self, intptr_t slot);
void QListView_virtualbase_CloseEditor(void* self, QWidget* editor, int hint);
extern __declspec(dllexport) void QListView_override_virtual_CommitData(void* self, intptr_t slot);
void QListView_virtualbase_CommitData(void* self, QWidget* editor);
extern __declspec(dllexport) void QListView_override_virtual_EditorDestroyed(void* self, intptr_t slot);
void QListView_virtualbase_EditorDestroyed(void* self, QObject* editor);
extern __declspec(dllexport) void QListView_override_virtual_Edit2(void* self, intptr_t slot);
bool QListView_virtualbase_Edit2(void* self, QModelIndex* index, EditTrigger trigger, QEvent* event);
extern __declspec(dllexport) void QListView_override_virtual_SelectionCommand(void* self, intptr_t slot);
int QListView_virtualbase_SelectionCommand(const void* self, QModelIndex* index, QEvent* event);
extern __declspec(dllexport) void QListView_override_virtual_FocusNextPrevChild(void* self, intptr_t slot);
bool QListView_virtualbase_FocusNextPrevChild(void* self, bool next);
extern __declspec(dllexport) void QListView_override_virtual_ViewportEvent(void* self, intptr_t slot);
bool QListView_virtualbase_ViewportEvent(void* self, QEvent* event);
extern __declspec(dllexport) void QListView_override_virtual_MousePressEvent(void* self, intptr_t slot);
void QListView_virtualbase_MousePressEvent(void* self, QMouseEvent* event);
extern __declspec(dllexport) void QListView_override_virtual_MouseDoubleClickEvent(void* self, intptr_t slot);
void QListView_virtualbase_MouseDoubleClickEvent(void* self, QMouseEvent* event);
extern __declspec(dllexport) void QListView_override_virtual_DragEnterEvent(void* self, intptr_t slot);
void QListView_virtualbase_DragEnterEvent(void* self, QDragEnterEvent* event);
extern __declspec(dllexport) void QListView_override_virtual_FocusInEvent(void* self, intptr_t slot);
void QListView_virtualbase_FocusInEvent(void* self, QFocusEvent* event);
extern __declspec(dllexport) void QListView_override_virtual_FocusOutEvent(void* self, intptr_t slot);
void QListView_virtualbase_FocusOutEvent(void* self, QFocusEvent* event);
extern __declspec(dllexport) void QListView_override_virtual_KeyPressEvent(void* self, intptr_t slot);
void QListView_virtualbase_KeyPressEvent(void* self, QKeyEvent* event);
extern __declspec(dllexport) void QListView_override_virtual_InputMethodEvent(void* self, intptr_t slot);
void QListView_virtualbase_InputMethodEvent(void* self, QInputMethodEvent* event);
extern __declspec(dllexport) void QListView_override_virtual_EventFilter(void* self, intptr_t slot);
bool QListView_virtualbase_EventFilter(void* self, QObject* object, QEvent* event);
extern __declspec(dllexport) void QListView_Delete(QListView* self, bool isSubclass);

} 
